"""Content for the Extended Response Workbook (Paper 1 Q4). All passages are original."""

PASSAGES = [
 dict(n=1, guided=True, form="journal", title="The Last Watch",
  paras=[
   "My father kept the lighthouse at Ras Hamra for twenty-six years, and on the night before it became automatic, he let me stay up with him for the last watch.",
   "The lamp room was warm and smelled of brass polish and paraffin, although the great lamp had not burned paraffin for decades. My father still polished the lens every evening, turning the cloth in slow circles across the glass prisms, as if it might notice if he stopped. ‘Tomorrow a computer does this,’ he said. ‘It will never be late and it will never fall asleep. And it will never care.’",
   "He showed me the logbook, its pages filled with his small, neat handwriting: weather, passing ships, the night a fishing boat lost its engine and he guided it in with the signal lamp, flashing instructions until three in the morning. He had never told me that story. He had saved four lives, and he had written it down in two lines, between a note about wind speed and a reminder to order more oil.",
   "At midnight we stood on the gallery outside. The wind pulled at our jackets and the beam swept over the dark water, round and round, like a slow, patient heartbeat. Far out, the lights of a tanker slid past. ‘They’ll never know,’ my father said, ‘that it’s the last night anybody watches for them.’",
   "At dawn, engineers arrived in a white van. They were polite and young and in a hurry. My father handed over the keys, shook their hands, and then walked down the spiral stairs without looking back.",
   "Only later, in the car, did I notice that he had taken the logbook with him, tucked inside his coat like something alive.",
  ],
  task="Imagine you are the lighthouse keeper. That evening, after leaving the lighthouse for the last time, you write a journal entry.",
  bullets=["describe your final night and morning at the lighthouse",
           "explain what the job has meant to you, including the night of the fishing boat",
           "reflect on your feelings about the lighthouse becoming automatic, and about your future."],
  ideas=[("Bullet 1", "Polishing the lens one last time; the warm lamp room, brass and paraffin; sharing the watch with his daughter; the gallery at midnight, wind, the sweeping beam, a passing tanker; engineers at dawn, handing over the keys, leaving without looking back."),
         ("Bullet 2", "Twenty-six years of care; the logbook as a record of his life; the fishing boat – guiding it in until 3 a.m., saving four lives, yet recording it in two lines (modesty); the job as watching over others."),
         ("Bullet 3 (development)", "Machines are reliable but “will never care”; sadness, pride, perhaps resentment of the hurried engineers; taking the logbook – unable to let go; uncertainty about life without a purpose; perhaps closer to his daughter now.")],
  model=["<i>Thursday, late</i>",
   "So it is done. Twenty-six years, and it ended with a handshake and a white van.",
   "I polished the lens one last time tonight. I know it is foolish – the lens does not care who cleans it – but my hands wanted to do it. My daughter stayed up with me for the last watch. I think she was surprised how quiet it was. We stood on the gallery at midnight, the wind tearing at our jackets, and I watched a tanker slide past and thought: they have no idea that nobody will be watching for them tomorrow.",
   "I showed her the logbook. She found the night of the fishing boat, and I could see she didn’t understand why I had never mentioned it. What was there to say? The engine failed, the sea was rising, and I stood at the signal lamp until three in the morning. Four men went home to their families. That was the job. Not the brass or the polish, but that: being awake when others needed someone to be.",
   "The engineers were pleasant enough. Young, in a hurry, already thinking of the next lighthouse on their list. The computer will be perfect, they tell me. It will never be late and it will never fall asleep. I believe them. But it will never care, and I don’t know how to explain to them why that matters.",
   "I took the logbook. I am not sure it was mine to take, but I could not leave it in a drawer for nobody to read.",
   "Tomorrow I will wake up with nothing to watch. Perhaps I will learn to sleep through the night. Perhaps I won’t."],
  why=["Journal conventions: date, first person, private and reflective tone.",
       "All three bullets covered, woven together rather than answered as a list.",
       "Develops the text: explains why he never mentioned the rescue (modesty, duty).",
       "Convincing voice: short sentences, understated emotion, echoes of his own words (“it will never care”).",
       "An ending that looks to the future with honest uncertainty."]),
 dict(n=2, guided=True, form="report", title="The Garden Behind the Science Block",
  paras=[
   "For as long as anyone could remember, the strip of land behind the science block had been a dumping ground: broken chairs, a rusting bicycle, weeds taller than the Year 7s. Then, last September, Ms Adebayo, our biology teacher, asked for volunteers to turn it into a garden. Eleven of us turned up. By October, only six remained.",
   "The first month was brutal. We hauled out three skips of rubbish, including, mysteriously, a piano stool. The soil was so hard and dry that our spades bounced off it. We learned, painfully, that you cannot simply scatter seeds and hope: our first planting of beans was eaten overnight by pigeons, and a heatwave killed most of the lettuce.",
   "Ms Adebayo refused to let us give up. She showed us how to build raised beds from old pallets, how to make compost from canteen food waste, and how to set up a simple drip-watering system using recycled bottles, which cut our water use dramatically. A local garden centre donated seedlings after we wrote to them, and the caretaker, who had seemed grumpy for years, turned out to know everything about tomatoes.",
   "By March, the garden was unrecognisable. We had herbs, tomatoes, peppers and a small patch of sunflowers that became a favourite spot for students to sit at lunch. The canteen began using our herbs, and younger students started asking if they could join. Two students who had struggled with attendance, it was noticed, never missed a Tuesday gardening session.",
   "There are still problems. Over the summer holidays, nobody will be here to water the plants, and the pallets are already beginning to rot. But on the last day of term, when we picked our first proper harvest, even the pigeons seemed impressed.",
  ],
  task="Imagine you are one of the students in the gardening group. The head teacher has asked you to write a report on the garden project.",
  bullets=["explain how the garden was created and the problems the group faced",
           "describe the benefits the garden has brought to the school",
           "recommend what should happen next, including how to solve the remaining problems."],
  ideas=[("Bullet 1", "Neglected dumping ground; Ms Adebayo’s call for volunteers; eleven reduced to six; three skips of rubbish; hard, dry soil; pigeons ate the beans; heatwave killed the lettuce; solutions – raised beds from pallets, compost from canteen waste, drip-watering from bottles; donated seedlings; the caretaker’s expertise."),
         ("Bullet 2", "Herbs, tomatoes, peppers; sunflower area popular at lunch; herbs used by the canteen; younger students want to join; improved attendance among students who had struggled; water saved; community links (garden centre, caretaker)."),
         ("Bullet 3 (development)", "Summer watering rota; replacing rotting pallets with durable beds; recruiting younger students to sustain the group; recognising volunteers; further partnerships – recommendations should grow logically from the problems in the text.")],
  model=["<b>Report to the Head Teacher: The Science Block Garden</b><br><i>From: Student Gardening Group</i>",
   "<b>Purpose</b><br>This report explains how the garden was created, describes its benefits and recommends next steps.",
   "<b>How the garden was created</b><br>Last September, Ms Adebayo invited volunteers to transform the neglected land behind the science block. Six committed students cleared three skips of rubbish before any planting could begin. The group faced serious setbacks: the soil was hard and dry, pigeons ate the first crop of beans and a heatwave destroyed most of the lettuce. These problems were overcome by building raised beds from recycled pallets, making compost from canteen waste and installing a drip-watering system made from bottles, which greatly reduced water use. A local garden centre donated seedlings, and the caretaker provided expert advice.",
   "<b>Benefits to the school</b><br>The garden now produces herbs, tomatoes and peppers, and the canteen uses our herbs. The sunflower area has become a popular place at lunchtime. The project has also encouraged involvement: younger students want to join, and attendance on gardening days has been excellent, including among students who have previously struggled to attend.",
   "<b>Remaining problems</b><br>There is no plan for watering during the summer holidays, and the pallets are beginning to rot.",
   "<b>Recommendations</b><br>1. Create a summer watering rota of staff, families and students, supported by the caretaker.<br>2. Replace the pallets with longer-lasting raised beds, perhaps with further help from the garden centre.<br>3. Open the group to younger students so the project continues when current members leave.",
   "<b>Conclusion</b><br>The garden has turned a dumping ground into a valuable resource. With modest investment, it can continue to grow."],
  why=["Full report conventions: title, sender, purpose, subheadings, numbered recommendations.",
       "Formal, objective register – the humour of the original (the piano stool, the pigeons) is left out.",
       "Selects and reorganises details under headings, rather than retelling in order.",
       "Infers benefits (attendance, community links) from details in the text.",
       "Recommendations respond directly to the problems identified."]),
 dict(n=3, guided=True, form="interview", title="Night on the Mountain",
  paras=[
   "The call came at 7.40 p.m.: two hikers, a father and his teenage son, overdue on the ridge path above the village. The temperature was dropping fast, and cloud had swallowed the upper slopes. By eight, Yusuf and three other volunteers from the mountain rescue team were climbing into the dark with headtorches, ropes and a stretcher.",
   "Yusuf had been a rescuer for nine years. By day, he fixed air-conditioning units; by night, when the phone rang, he became someone else entirely. ‘You don’t think about being tired,’ he told me later. ‘You think about the person who is colder than you.’",
   "The search took four hours. The team followed the path until it vanished beneath loose rock, then spread out in a line, calling into the mist. Their voices seemed to disappear as soon as they left their mouths. Twice they found nothing but an abandoned water bottle and a torn map.",
   "At midnight, one of the team saw a faint, flickering light below the ridge. The father had slipped and injured his ankle; his son had wrapped him in every piece of clothing they had and was flashing his phone torch at the sky every few minutes, just as a first-aid course at school had taught him. The boy was shivering so hard he could barely speak, but he had not left his father’s side.",
   "Carrying the father down took another three hours. The path was steep and slippery, and the team took turns at the stretcher, inching forward, calling out each rock and root. They reached the village at 3.15 a.m., where the boy’s mother was waiting with blankets and tears.",
   "Yusuf went home, slept for two hours, and went to work. ‘The son was the real hero,’ he said. ‘We just did the carrying.’",
  ],
  task="Imagine you are Yusuf. A few days later, you are interviewed for a local radio programme about the rescue. Write the interview.",
  bullets=["describe what happened during the search and rescue",
           "explain what it is like to be a volunteer rescuer",
           "reflect on why you think the son was “the real hero” and what others could learn from him."],
  ideas=[("Bullet 1", "Call at 7.40 p.m.; falling temperature and cloud; four volunteers with torches, ropes, stretcher; four-hour search; path lost in loose rock; line search in mist; the bottle and torn map; the flickering light at midnight; three-hour carry; arrival at 3.15 a.m.; the mother waiting."),
         ("Bullet 2", "Nine years as a volunteer alongside a day job; becoming “someone else”; thinking of the person colder than you; exhaustion, teamwork, taking turns; two hours’ sleep then work."),
         ("Bullet 3 (development)", "The son stayed with his father, kept him warm and made himself visible – that is why they were found; used first aid learned at school; humility (“we just did the carrying”); a message about learning first aid and staying calm.")],
  model=["<b>Presenter:</b> Yusuf, thank you for joining us. Take us back to that evening.",
   "<b>Yusuf:</b> We got the call just before eight. A father and son were overdue on the ridge path. The temperature was falling and the cloud had come right down, so we knew we had to move quickly. Four of us set off with headtorches, ropes and a stretcher.",
   "<b>Presenter:</b> How difficult was the search?",
   "<b>Yusuf:</b> Very. After a while the path disappears under loose rock, so we spread out in a line and called. In that mist your voice just vanishes. We found a water bottle and a torn map, which is a horrible feeling, because it tells you someone has been there but not where they are now. Then, around midnight, one of the team spotted a tiny light flashing below the ridge.",
   "<b>Presenter:</b> That was the son?",
   "<b>Yusuf:</b> It was. His father had injured his ankle, and the boy had wrapped him in every layer they had and kept signalling with his phone, like he’d learned in first aid at school. He was shaking so badly he couldn’t talk, but he wouldn’t leave his dad.",
   "<b>Presenter:</b> You’re a volunteer. Why do you do it?",
   "<b>Yusuf:</b> By day I fix air-conditioning units. When the phone rings, you become someone else. You don’t think about being tired; you think about the person who is colder than you. Carrying someone down for three hours in the dark is exhausting, but you share it, and you get them home.",
   "<b>Presenter:</b> You’ve called the son the real hero.",
   "<b>Yusuf:</b> Because he was. He stayed calm, he kept his father warm and he made himself visible. That’s why we found them. If young people take one thing from this, it’s to learn basic first aid. It saved a life."],
  why=["Interview conventions: clear speaker labels; purposeful questions that steer through the bullets.",
       "Developed answers in a natural spoken voice, not a list of facts.",
       "Adds convincing inference (why the bottle and map were a “horrible feeling”).",
       "Keeps Yusuf’s modesty from the text while explaining clearly why the son was the hero.",
       "Ends with a clear message for listeners."]),
 dict(n=4, guided=False, form="speech", title="After the Fire",
  paras=[
   "The fire started just after closing time on a Thursday in March, probably from a faulty cable behind the spice stalls. By the time the fire engines forced their way through the narrow lanes, flames were leaping from the wooden roofs, and the air was thick with the smell of burning cardamom and plastic. Nobody was hurt. But by morning, forty-one of the market’s sixty stalls were blackened frames, and years of stock had turned to ash.",
   "Mariam Saleh, who had sold fabrics there for twenty years, stood in the wet ashes and cried. Then she started making lists. Within a week, she and a small group of traders had set up temporary tables in the car park next door, so that customers would not forget them. Neighbours brought flasks of tea. A local radio station ran an appeal, and donations arrived from people who had not visited the market in years – and some who had never visited at all.",
   "Rebuilding was slow. Insurance covered only some of the losses, and several older traders decided they could not start again. There were arguments about the new design: some wanted the old narrow lanes back; others wanted wider paths, a proper sprinkler system and electrical wiring that met modern standards. In the end, the council agreed to a compromise: the familiar layout, with safety built in.",
   "Six months later, the market reopened. The new roofs are metal, the cables are hidden in fireproof ducts, and there are sprinklers above every stall. But the smells are the same, and so is the noise. On the first morning, Mariam hung a single scorched piece of silk above her stall. ‘So we remember,’ she said, ‘and so we don’t give up.’",
  ],
  task="Imagine you are Mariam Saleh. You have been asked to give a speech at the reopening of the market.",
  bullets=["describe the night of the fire and the days that followed",
           "explain how the market was rebuilt and the difficult decisions involved",
           "thank the people who helped, and express your hopes for the future."],
  ideas=[("Bullet 1", "Fire after closing time from a faulty cable; engines struggling through narrow lanes; burning roofs; smell of cardamom and plastic; nobody hurt; 41 of 60 stalls destroyed; Mariam crying, then making lists; temporary tables in the car park within a week."),
         ("Bullet 2", "Slow rebuilding; insurance covered only part; some older traders gave up; arguments over narrow lanes versus wider paths and safety; the council’s compromise – familiar layout with metal roofs, fireproof ducts, sprinklers."),
         ("Bullet 3 (development)", "Thanks to neighbours (tea), the radio station, donors old and new, the council, firefighters, customers; the scorched silk as a symbol of memory and resilience; hopes that the market thrives, stays safe and keeps its character.")],
  model=["Friends, neighbours, customers – welcome back.",
   "Six months ago, I stood right here in the wet ashes and cried. The fire had started after closing time, probably from a faulty cable, and by morning forty-one of our sixty stalls were nothing but black frames. Twenty years of my own fabrics were gone. Many of you lost far more. Thank God, nobody was hurt – but for a while, it felt as if the heart of our neighbourhood had stopped.",
   "Then something remarkable happened. Within a week we were trading again from tables in the car park, because we refused to let you forget us. And you didn’t. You brought us tea. You bought a scarf you didn’t need. When the radio appeal went out, donations came from people who hadn’t visited in years, and even from people who had never been here at all.",
   "Rebuilding was not easy, and I won’t pretend it was. The insurance did not cover everything, and some of our oldest traders decided they could not start again. We miss them today. We argued, too – about narrow lanes and wide paths, about keeping the old market or making a safer one. In the end, we found a way to have both: the layout you love, with metal roofs, protected wiring and sprinklers above every stall.",
   "So thank you – to the firefighters, to the council, to the radio station, and above all to every one of you who came back.",
   "Above my stall hangs one scorched piece of silk. It is there so we remember, and so we never give up. Smell the spices. Listen to the noise. Our market is alive again, and with your help, it will be here for years to come."],
  why=["Speech conventions: direct address, inclusive “we” and “you”, a rousing close.",
       "Moves from memory to gratitude to hope – a clear emotional structure.",
       "Develops the text with convincing, in-character detail (“You bought a scarf you didn’t need”).",
       "Honest about difficulties, which makes the celebration more credible.",
       "Uses the scorched silk from the text as a powerful closing symbol."]),
 dict(n=5, guided=False, form="letter", title="Three Weeks in Kyoto",
  paras=[
   "When Hana arrived at her host family’s house in Kyoto, she bowed so low and so nervously that she nearly toppled into the umbrella stand. Mrs Tanaka laughed – kindly – and steadied her by the elbow, and that was how the exchange began.",
   "The first week was exhausting. Hana had studied Japanese for two years at school, but real conversation came too fast, full of words that were not in her textbook. At dinner she smiled and nodded, understanding perhaps a third of what was said. She got lost twice on the way to school and once, memorably, bought a train ticket to entirely the wrong city before a station guard rescued her.",
   "Small customs caught her out. She wore her outdoor shoes one step too far into the house, left her chopsticks standing upright in her rice – which, she learned, is associated with funerals – and forgot to take off the toilet slippers before returning to the living room. Each time, the family corrected her gently, and each time she felt her face burn.",
   "But in the second week, something shifted. Her host sister, Yui, who was fourteen and shy, began teaching her the words teenagers actually used. Grandfather Tanaka, who spoke no English, showed her how to fold paper cranes, guiding her fingers without a word. On a rainy Sunday, the whole family took her to a temple where the moss glowed green and the only sound was water dripping from the roofs.",
   "By the third week, Hana was dreaming in Japanese – badly, but still. On her last evening, Yui gave her a thousand paper cranes strung together, which the whole family had folded in secret. At the airport, Hana bowed again. This time, she did not wobble at all.",
  ],
  task="Imagine you are Hana. A week after returning home, you write a letter to the Tanaka family.",
  bullets=["describe your first impressions and the mistakes you made in the first week",
           "explain how each member of the family helped you",
           "reflect on what the exchange has meant to you and your hopes for the future."],
  ideas=[("Bullet 1", "The nervous bow and near-fall; Mrs Tanaka’s kindness; exhaustion; understanding a third at dinner; getting lost; the wrong-city ticket; the shoes, the chopsticks and the toilet slippers; embarrassment and gentle correction."),
         ("Bullet 2", "Mrs Tanaka steadied and welcomed her; Yui taught real teenage language; Grandfather taught paper cranes without words; the family’s temple trip; the thousand cranes folded in secret."),
         ("Bullet 3 (development)", "Growing confidence (dreaming in Japanese, the steady bow); gratitude; the value of patience and kindness across languages; hopes to return or to host Yui; continuing to study Japanese.")],
  model=["Dear Mr and Mrs Tanaka, Yui and Grandfather,",
   "I have been home for a week now, and I still stop at the front door to take off my shoes! I wanted to write to thank you properly, because at the airport I was too emotional to find the right words in any language.",
   "Do you remember my first minute in your house? I bowed so nervously that I nearly fell into the umbrella stand. Mrs Tanaka, you laughed and caught my elbow, and suddenly I didn’t feel quite so frightened. The first week was harder than I expected. I understood perhaps a third of what you said at dinner, I got lost on the way to school, and I will never forget buying a ticket to completely the wrong city. I am still embarrassed about my chopsticks standing in my rice, and about wearing the toilet slippers into the living room. Thank you for correcting me so gently.",
   "Each of you helped me in your own way. Yui, you taught me the words real teenagers use – my Japanese teacher here was very surprised! Grandfather, you showed me how to fold paper cranes without saying a single word, and I think that was the best lesson of all. And the rainy afternoon at the temple, with the green moss and the sound of dripping water, is the most peaceful memory I have.",
   "The thousand cranes are hanging above my bed. When I look at them, I remember that you folded them in secret for a clumsy girl who could barely speak to you.",
   "I am saving to come back next summer, and I hope that one day Yui will visit us here.",
   "With love and gratitude,<br>Hana"],
  why=["Letter conventions: warm greeting to each family member, clear purpose, affectionate sign-off.",
       "Humour and embarrassment used in Hana’s own voice, not retold from outside.",
       "Every family member’s help is covered, as bullet 2 requires.",
       "Develops the cranes into a symbol of the family’s kindness.",
       "Ends with specific, believable hopes for the future."]),
 dict(n=6, guided=False, form="article", title="The Robot That Wouldn’t Turn Left",
  paras=[
   "The robot was called Falcon, and three days before the regional robotics competition, it could not turn left.",
   "It could drive forwards beautifully. It could turn right with elegant precision. But ask it to turn left and it spun in a slow, apologetic circle, like a dog chasing its tail. The team – five students from Year 10 who had spent every lunchtime since January building it – tried everything. They rewrote the code, replaced a motor and, at one point, in desperation, tried switching it off and on again.",
   "On the morning of the competition, Falcon still would not turn left. Priya, the team’s programmer, had barely slept. ‘We could plan the whole route so we only turn right,’ suggested Ben, half joking. Nobody laughed. Then everybody looked at each other.",
   "It was an absurd idea. The challenge required the robot to collect coloured blocks from around an arena and return them to base, and every other team planned efficient routes with left and right turns. Falcon would have to take the long way round everything, making three right turns every time it needed to go left. It would be slower. But it would work.",
   "In the first round, Falcon looked ridiculous, circling the arena like a lost tourist, and the audience laughed. But the robots that tried the fastest routes kept crashing into walls and into each other. Falcon, slow and steady and turning only right, never crashed once. By the final round, the laughter had turned into cheering.",
   "They came second. In the car park afterwards, a judge found them and said the team had shown ‘the best problem-solving of the day’. On the journey home, Priya finally found the bug: a single minus sign in the wrong place.",
  ],
  task="Imagine you are a member of the robotics team. Write an article for your school magazine about the competition.",
  bullets=["describe the problem with the robot and how the team tried to fix it",
           "explain the team’s unusual solution and what happened at the competition",
           "reflect on what the team learned from the experience."],
  ideas=[("Bullet 1", "Falcon could drive forwards and turn right but spun in circles on left turns; five Year 10 students; every lunchtime since January; rewriting code, replacing a motor, switching off and on; Priya’s lack of sleep."),
         ("Bullet 2", "Ben’s half-joke; the right-turns-only route – three rights for every left; slower but reliable; laughter in round one; rivals crashing; cheering by the final; second place; the judge’s praise; the bug – a single minus sign."),
         ("Bullet 3 (development)", "Reliability can beat speed; creative thinking under pressure; teamwork and listening to unlikely ideas; resilience after months of work; humour and humility; small errors can have big effects.")],
  model=["<b>Right Turn Only: How Falcon Flew to Second Place</b>",
   "Three days before the regional robotics competition, our robot had a problem. It could drive forwards perfectly. It could turn right with real precision. But ask Falcon to turn left and it spun in slow, embarrassing circles, like a dog chasing its tail.",
   "Our team of five Year 10 students had spent every lunchtime since January building it, so you can imagine the panic. We rewrote the code, replaced a motor and, in desperation, tried switching it off and on again. Nothing worked. Priya, our programmer, hardly slept.",
   "On the morning of the competition, Ben half-jokingly suggested that we plan our route so that Falcon only ever turned right. Nobody laughed – because we realised it might actually work. Every left turn would become three right turns. We would be slower than everyone else, but we would get there.",
   "In the first round, the audience laughed as Falcon wandered around the arena like a lost tourist. But the teams who chose the fastest, riskiest routes kept crashing into walls and into each other. Falcon never crashed once. By the final round, the laughter had turned into cheering, and we finished second in the whole region. One judge told us we had shown “the best problem-solving of the day”.",
   "The final twist? On the drive home, Priya found the bug: a single minus sign in the wrong place.",
   "We learned that a plan that works matters more than a perfect plan, that slow and steady really can beat fast and reckless, and that the best ideas sometimes start as jokes. Next year, Falcon will turn left. Probably."],
  why=["Article conventions: a witty headline, an engaging opening, lively paragraphs, a strong final line.",
       "First-person plural (“we”, “our team”) fits a team member writing for the school.",
       "Selects and shapes events for suspense rather than retelling every detail.",
       "Clear reflection on lessons learned, developed beyond the text.",
       "Humour suits the school-magazine audience."]),
]

LADDER = [("Retelling", "The keeper saved four lives from a fishing boat."),
          ("Using", "I once guided a fishing boat home and saved four men."),
          ("Developing", "Four men went home to their families. That was the job."),
          ("Inferring in voice", "Not the brass or the polish, but that: being awake when others needed someone to be.")]
