"""Content for the IGCSE 0500 Paper 1 Practice Pack, Volume 2 (Sets 4-6). All texts are original."""

META = dict(out="IGCSE-0500-Paper-1-Practice-Pack-Vol-2-2027.pdf", title="Practice Pack 2",
            footer="IGCSE 0500 Paper 1 Practice Pack · Volume 2",
            extra_css=".text .body{font-size:10.5pt;line-height:1.52}.text .body p{margin-bottom:7px}")

SETS = [
# ───────────────────────────── SET 4 ─────────────────────────────
dict(
 n=4, theme="Journeys",
 A=dict(title="The Night Bus", kind="Fiction", paras=[
  "The bus left at ten, and by eleven Nadia had read every sign on it twice. NO SMOKING. KEEP YOUR BELONGINGS WITH YOU. EMERGENCY EXIT. She had never travelled alone before, and she found that reading was easier than thinking about why she was travelling at all.",
  "Her grandmother was ill. That was all her mother had said on the phone, in a voice so careful that it frightened Nadia more than any detail could have.",
  "The seat beside her was taken by an old man in a grey jacket who smelled faintly of cardamom and engine oil. He nodded to her once, folded his hands across his stomach and appeared to fall instantly asleep.",
  "At two in the morning, somewhere in the middle of the desert, the bus shuddered, coughed and stopped.",
  "For a moment nobody moved. Then the lights flickered off, and a groan passed through the passengers like a wave. The driver climbed down with a torch. Somewhere behind her, a baby began to wail.",
  "The old man opened his eyes. “Fuel pump,” he said, as calmly as if he were announcing the weather. “I drove this route for thirty-one years. It’s always the fuel pump.”",
  "He climbed down after the driver, and Nadia, not wanting to be left alone in the dark, followed.",
  "Outside, the cold took her breath away. But when she looked up, she forgot about the cold completely. The sky was crowded with stars – not the handful she saw above the city, but thousands upon thousands of them, so thick and bright that they seemed to hang just above her head, close enough to touch.",
  "While the two men bent over the engine, murmuring to each other in the torchlight, the passengers drifted out one by one. Someone produced a flask of tea. A student shared a packet of biscuits. The baby, carried outside by its mother, stopped crying and stared up at the sky with its mouth open.",
  "When the old man came back, wiping his hands on a rag, he stood beside Nadia and pointed upwards. He named the stars for her, one by one, the way her grandmother used to name the plants in her garden, and Nadia realised that her fear had quietly loosened its grip.",
  "The engine roared back into life at half past three. The passengers cheered.",
  "They reached the city just after dawn. As she stepped down onto the pavement, the old man touched her arm. “Your grandmother,” he said. “Tell her you saw the stars.” Nadia had not told him anything about her grandmother. She turned to ask him how he knew, but he had already disappeared into the crowd.",
 ]),
 B=dict(title="All Aboard: Why Slow Travel Is Speeding Up", kind="Magazine article", paras=[
  "For most of the last fifty years, the story of travel has been a story of speed. Faster planes, cheaper flights and bigger airports have made it possible to have breakfast on one continent and dinner on another. Yet a growing number of travellers are deliberately choosing to go slowly – by train, by ferry, even by bicycle – and taking days to complete journeys they could fly in hours.",
  "The most common reason they give is the environment. A short-haul flight produces many times more carbon dioxide per passenger than the same journey by train, and for travellers who worry about climate change, that difference has become hard to ignore. Some people have given up flying entirely; others simply fly less and choose rail wherever a reasonable route exists.",
  "But it is not only about guilt. Many slow travellers say the journey itself has become the best part of the trip. From a train window you see the landscape change gradually – cities giving way to farmland, farmland to mountains – in a way that is impossible from thirty thousand feet. There is time to read, to think, to talk to strangers. One regular rail traveller told me that she had made more friends on overnight trains than in ten years of flying.",
  "Comfort plays a part too. Airports have become places of queues, security checks and delays, where passengers must arrive hours before departure. Stations, by contrast, are usually in city centres, and boarding takes minutes. On a long-distance train you can walk around, eat a proper meal and arrive without the exhausting stiffness of a flight. The return of night trains in several countries means travellers can fall asleep in one city and wake up in another, saving the cost of a hotel.",
  "There are obstacles, of course. Train tickets are often more expensive than budget flights, and booking a journey that crosses several countries can be bewilderingly complicated. Slow travel also takes time, which many people, with limited holidays, simply do not have. For long distances across oceans, there is still no realistic alternative to flying.",
  "Still, the direction of change is clear. Rail companies are investing in new routes, and a younger generation seems more interested in experiences than in ticking off destinations. Perhaps we are rediscovering something our grandparents knew: that the point of a journey is not only to arrive.",
 ]),
 C=dict(title="Lost in Shinjuku", kind="Travel memoir", paras=[
  "I had prepared for Tokyo the way some people prepare for exams. I had studied maps, memorised the train lines in their bright spaghetti of colours, and practised the same six Japanese phrases until I could say them in my sleep. None of it prepared me for Shinjuku Station at eight o’clock on a Monday morning.",
  "It was less a station than a small city buried underground. Corridors branched and rejoined, rose and plunged, each one lined with shops and signs and yet more corridors. And through all of it flowed people – thousands of them, perhaps tens of thousands – moving with a speed and certainty that made me feel like a pebble dropped into a river. Nobody pushed. Nobody shouted. They simply parted around me and closed again, a <b>relentless</b> tide of dark suits and briefcases, while announcements chimed overhead in a language my six phrases did not begin to cover.",
  "I stood by a pillar clutching my map, which had become useless the moment I stepped off the train. My exit was somewhere to the west, but the station had over two hundred exits, and I had apparently chosen the wrong end of all of them. My suitcase felt like an anchor. My face grew hot. I was, I realised, about to cry in one of the busiest railway stations on Earth.",
  "That was when a small, elderly woman in a lilac cardigan stopped in front of me. She looked at my map, then at my face, and said something gentle that I did not understand. I showed her the name of my hotel. She nodded <b>decisively</b>, as though I had asked her to solve a problem she had been waiting all morning to solve, and set off through the crowd.",
  "I followed her for fifteen minutes. She never hurried and never hesitated, turning left and right through the maze with total confidence, glancing back now and then to make sure I was still there. She led me up a staircase, along a corridor I would never have found, and out into sudden daylight, where the glass towers of the city reflected a clear blue sky. She pointed across the road to my hotel, bowed slightly, and before I could find the words to thank her properly, she had turned and walked back into the station.",
  "She had not been going that way at all.",
  "I stayed in Tokyo for three weeks. I saw temples and gardens, ate food I still dream about and stood under cherry trees in full blossom. But the moment I remember most clearly is a stranger in a lilac cardigan, walking back the way she had come.",
 ]),
 Q1=[
  ("Why does Nadia read every sign on the bus twice?", 2),
  ("“…in a voice so careful that it frightened Nadia more than any detail could have.” What does this suggest about Nadia’s mother and the grandmother’s illness?", 2),
  ("Give <b>two</b> details which suggest that the old man has a connection with buses or engines.", 2),
  ("Re-read paragraph 5. How do the passengers react when the bus stops?", 2),
  ("Explain what the writer suggests by the comparison “as calmly as if he were announcing the weather”.", 2),
  ("Using your own words, explain how the night sky in the desert is different from the sky Nadia normally sees.", 2),
  ("Re-read paragraph 9. How does the mood among the passengers change? Refer to <b>two</b> details.", 3),
  ("Why does the writer compare the old man naming the stars to Nadia’s grandmother naming plants, and what effect does this have on Nadia?", 2),
  ("Explain why the ending is surprising, and what it might suggest about the old man.", 3),
 ],
 Q1_ms=[
  "To distract herself / avoid thinking about her grandmother’s illness (1); she is nervous about travelling alone (1).",
  "The mother is choosing her words carefully / hiding her fear to protect Nadia (1); this suggests the illness is serious (1).",
  "Any two: he smells of engine oil; he drove this route for thirty-one years; he knows at once it is the fuel pump; he helps the driver repair the engine (1 each).",
  "Stunned silence at first (“nobody moved”) (1); then groaning / frustration / dismay; the baby cries (1).",
  "He is completely unworried / relaxed (1); the breakdown is routine to him because of his experience, which is reassuring (1).",
  "There are far more stars – thousands rather than a handful (1); they seem brighter, denser and very close, as if they could be touched (1).",
  "Up to 3: the mood shifts from frustration to warmth / community (1); people share tea and biscuits (1); even the baby stops crying and gazes in wonder – calm replaces tension (1).",
  "It links the stranger to her grandmother, making him seem familiar and comforting (1); her fear eases (1).",
  "Up to 3: Nadia never told him about her grandmother, so his words are unexpected (1); he may have guessed or overheard, or there may be something almost mysterious or protective about him (1); he vanishes before she can ask, leaving the reader wondering and emphasising the kindness of strangers (1).",
 ],
 Q2a=("According to Text B, why are more people choosing slow travel?", [
  "concern about the environment / climate change",
  "flights produce far more carbon dioxide than trains",
  "the journey itself becomes the best part of the trip",
  "you see the landscape change gradually",
  "time to read and think",
  "chance to talk to strangers / make friends",
  "airports involve queues, security checks and delays",
  "you must arrive at airports hours early",
  "stations are usually in city centres",
  "boarding a train takes only minutes",
  "you can move around and eat a proper meal",
  "less physically tiring / no stiffness",
  "night trains let you sleep while travelling",
  "night trains save the cost of a hotel",
  "younger people value experiences over destinations",
 ]),
 Q2b=("What is the writer’s attitude towards slow travel? Explain how you can tell.", [
  "Enthusiastic: presents the journey as “the best part of the trip” and describes the view from the train warmly.",
  "Sympathetic to travellers’ motives: “it is not only about guilt” – treats their reasons with respect.",
  "Balanced / realistic: admits “there are obstacles, of course” – cost, complexity, time.",
  "Honest about its limits: “no realistic alternative to flying” across oceans.",
  "Optimistic: “the direction of change is clear”; ends by suggesting we are “rediscovering” a wiser idea of travel.",
 ]),
 Q3s=[
  ("Using your own words, explain what the following words mean as they are used in the text:<br>(i) <b>relentless</b> (paragraph 2)", 2),
  ("(ii) <b>decisively</b> (paragraph 4)", 2),
  ("Re-read paragraph 1. What does the comparison with preparing for exams suggest about the writer?", 2),
  ("Re-read paragraph 3. Why does the writer say the suitcase “felt like an anchor”?", 2),
  ("Re-read paragraph 6. Why do you think this sentence is placed in a paragraph on its own?", 2),
 ],
 Q3s_ms=[
  "Never stopping / constant / unceasing (2). Award 1 for “strong” or “fast”.",
  "Firmly / with certainty / without hesitation (2). Award 1 for “quickly”.",
  "The writer is thorough / organised / anxious to be ready (1); takes the trip very seriously, perhaps too seriously (1).",
  "It weighs the writer down / makes movement difficult (1); the writer feels stuck and unable to escape the situation (1).",
  "It emphasises the woman’s kindness / selflessness (1); it creates a moment of surprise and gives the realisation impact (1).",
 ],
 Q3l=("Re-read paragraphs 2 and 5. Explain how the writer uses language to convey the overwhelming nature of the station and the kindness of the woman who helps.", [
  ("Paragraph 2", [
   "“less a station than a small city buried underground” – vast, complex, hidden; a world of its own.",
   "“branched and rejoined, rose and plunged” – verbs in pairs create a maze-like, disorientating rhythm.",
   "“thousands of them, perhaps tens of thousands” – escalating numbers convey an overwhelming crowd.",
   "“like a pebble dropped into a river” – the writer is tiny, powerless and swept along.",
   "“Nobody pushed. Nobody shouted.” – short, repeated sentences: the order and calm make the writer feel even more out of place.",
   "“relentless tide of dark suits and briefcases” – water imagery continues; unstoppable, uniform, impersonal.",
  ]),
  ("Paragraph 5", [
   "“never hurried and never hesitated” – repetition stresses her calm, confident control.",
   "“total confidence” / “through the maze” – contrast with the writer’s confusion; she masters what defeated the writer.",
   "“glancing back… to make sure I was still there” – small detail showing care and attentiveness.",
   "“out into sudden daylight” – release, relief; light after the underground maze.",
   "“bowed slightly” – modest, respectful; she wants no thanks.",
   "“turned and walked back into the station” – quiet ending that sets up the revelation that she went out of her way.",
  ]),
 ]),
 Q4=("Imagine you are the writer of Text C. A travel magazine is running a series called ‘The Moment That Changed My Journey’ and interviews you about your first day in Tokyo. Write the interview.",
  ["describe how you prepared for Tokyo and what you expected",
   "explain what happened at Shinjuku Station and how you felt",
   "reflect on why this moment matters to you more than the famous sights you saw."],
  "interview",
  [("Bullet 1", "Studied maps; memorised train lines; practised six Japanese phrases; prepared as if for an exam – expected to cope, perhaps over-confident or anxious to be in control."),
   ("Bullet 2", "Monday rush hour; underground maze of corridors; enormous, orderly crowds; announcements not understood; map useless; over two hundred exits; heavy suitcase; hot face, close to tears. The elderly woman in a lilac cardigan; leading the way for fifteen minutes; daylight; pointing to the hotel; bowing and leaving before being thanked."),
   ("Bullet 3 (reflection – best answers develop this)", "She went out of her way (“had not been going that way at all”); kindness from a stranger without shared language; humility – preparation isn’t everything; the memory outlasts temples, gardens, food and cherry blossom; perhaps a wish to thank her or to help others in the same way.")]),
),
# ───────────────────────────── SET 5 ─────────────────────────────
dict(
 n=5, theme="The Natural World",
 A=dict(title="The Falcon", kind="Fiction", paras=[
  "Uncle Hamad’s falcon was called Barq, which means lightning, and for three weeks Khalid had been afraid of her.",
  "It was not only her talons, curved and black as thorns, or the hooked beak that could strip meat from a bone in seconds. It was her eyes. They were dark and bright and utterly without fear, and when she turned them on Khalid he had the uncomfortable sense of being measured and found wanting.",
  "“She knows you’re nervous,” said his uncle. “Birds always know. Stand still. Breathe. Let her decide.”",
  "So every evening, when the heat of the day had softened, Khalid stood in the yard with the thick leather glove on his left hand and a scrap of meat between his fingers, and waited. For days Barq ignored him completely. Then, one evening, she flew the short distance from her perch and landed on his fist with a weight that surprised him – heavier than she looked, and warm, and trembling with a power she was choosing not to use.",
  "By the end of the summer, Khalid could fly her. His uncle drove them out to the flat gravel plain beyond the farms, where the sky was enormous and empty. Khalid removed the little leather hood, felt Barq’s body tighten, and lifted his arm.",
  "She was gone in an instant – a dark shape climbing in wide circles until she was no bigger than a speck of ash. Khalid swung the lure, a bundle of feathers on a long cord, round and round his head, the way he had practised a hundred times. Barq should have seen it. She should have folded her wings and dropped like a stone.",
  "She did not come.",
  "Minutes passed. The speck drifted further and further away, towards the mountains, and then Khalid could not see it at all. His arm ached. His throat was tight. He thought of how much his uncle had paid for her, of the years he had spent training her, and of how he, Khalid, had lost her in a single afternoon.",
  "“Keep swinging,” said Uncle Hamad quietly. He had not moved from the car. He did not look angry. He looked, if anything, curious.",
  "So Khalid kept swinging, long after his shoulder burned and the sun had begun to sink. And just as he was about to give up, something flashed out of the gold light – a blur of wings and a rush of air – and Barq struck the lure so hard that the cord nearly tore from his hand.",
  "She stood on the feathers, panting, and looked up at him with those fearless eyes.",
  "“She was testing you,” said his uncle, and for the first time that summer, he smiled. “Now she knows you won’t give up on her.”",
 ]),
 B=dict(title="The Case for Trees", kind="Opinion article", paras=[
  "Stand on a city street at midday in summer and you will feel the difference a tree makes. In full sun, pavements can become hot enough to burn bare skin. Step into the shade of a large tree and the air feels several degrees cooler. Multiply that effect across a whole neighbourhood and trees become one of the most powerful tools a city has for coping with rising temperatures.",
  "Cooling is only the beginning. Trees filter dust and pollution from the air, and their roots soak up rainwater that would otherwise rush into drains and cause flooding. They provide homes and food for birds and insects, turning grey streets into living corridors for wildlife. They even reduce noise, softening the constant roar of traffic.",
  "The benefits for people are just as striking. Studies in several countries have linked green streets to lower levels of stress and better mental health. Patients in hospital rooms with a view of trees have been reported to recover more quickly. Children who grow up near green spaces tend to be more physically active. And tree-lined streets are, quite simply, places where people want to walk, shop and spend time – which is why homes and businesses on them are often worth more.",
  "Given all this, you might expect cities to be planting trees as fast as they can. Too often, the opposite happens. Mature trees are cut down to widen roads or make way for car parks, and replaced – if at all – with thin saplings that will take decades to offer the same shade. New developments are designed around cars and air-conditioning, with trees added as decoration at the end, if the budget allows. This is short-sighted in the extreme.",
  "There are real challenges. In hot, dry climates, trees need water, and choosing species that suit local conditions is essential. Roots can damage pipes and pavements if trees are planted carelessly. But none of these problems is new, and all of them can be solved with good planning.",
  "Some cities are showing the way, setting targets for tree cover and inviting residents to help plant and care for them. The lesson is clear: a tree is not an ornament. It is infrastructure, as essential as a road or a drain – and one of the few that grows more valuable with every passing year.",
 ]),
 C=dict(title="Hatchlings", kind="Memoir", paras=[
  "The volunteers met on the beach at nine, when the last colour had drained from the sky and the sea was only a sound – a long, slow breathing somewhere in the dark ahead of us. We were not allowed torches. Our guide, a marine biologist called Salma, explained that light confuses the turtles, and that from now on we must move slowly, speak softly and follow her exactly.",
  "For two hours, nothing happened. We sat in the sand, which still held a little of the day’s warmth, and waited. The stars came out in their thousands. A crab scuttled across my foot and I nearly screamed. I began to wonder whether the whole night would be a disappointment, and whether I would have been wiser to stay in bed.",
  "Then Salma touched my arm and pointed. At first I saw nothing. Then the sand a few metres away began to move. It trembled, sank a little, and suddenly erupted: dozens of tiny dark shapes came boiling up out of the ground, scrambling over one another, flippers flailing, each no bigger than the palm of my hand. They paused for a heartbeat on the surface, as if <b>bewildered</b> by the world, and then, all together, they turned towards the sea.",
  "I will never forget that journey across the sand. It could not have been more than thirty metres, but to them it must have seemed endless. They tumbled into footprints and struggled out again. They were flipped onto their backs by ridges no higher than a pencil and righted themselves with desperate, furious effort. A ghost crab darted from the shadows and seized one, and I had to stop myself from crying out. Salma shook her head gently: we were there to watch, not to interfere. The others pressed on, <b>undeterred</b>, drawn towards the faint silver glimmer of the waves as if pulled by an invisible thread.",
  "One by one, they reached the wet sand. The first wave washed over them and swept them backwards, and then the next carried them out, and they were gone – swallowed by the vast dark water where, Salma told us, only around one in a thousand would survive to become adults.",
  "We walked back up the beach in silence. I had come expecting to see something beautiful, and I had. But what stayed with me was not the beauty. It was the courage of creatures smaller than my hand, setting out alone into an enormous ocean, with every chance of failure and no hesitation at all.",
 ]),
 Q1=[
  ("What does the name Barq mean?", 1),
  ("Give <b>two</b> features of the falcon that make Khalid afraid of her.", 2),
  ("Using your own words, explain how Khalid feels when Barq looks at him.", 2),
  ("What does Uncle Hamad’s advice in paragraph 3 suggest about how a falcon should be trained?", 2),
  ("Re-read paragraph 4. Explain what surprises Khalid when Barq first lands on his fist, and what this suggests about her.", 3),
  ("Re-read paragraph 6. What does the comparison “no bigger than a speck of ash” suggest?", 2),
  ("Why do you think the writer places “She did not come.” in a paragraph of its own?", 2),
  ("Explain why Khalid feels so upset in paragraph 8.", 2),
  ("What does Uncle Hamad’s behaviour in paragraphs 9–12 suggest about him, and what does his final comment reveal?", 4),
 ],
 Q1_ms=[
  "Lightning (1).",
  "Any two: her talons (curved, black as thorns); her hooked beak (can strip meat from bone); her fearless eyes (1 each).",
  "He feels judged / assessed (1) and not good enough / inadequate; uncomfortable and self-conscious (1).",
  "Training needs patience and calm (1); the trainer must earn the bird’s trust and let her choose, rather than force her (1).",
  "Up to 3: she is heavier than she looks (1); she is warm and trembling (1); this suggests great strength or danger that she is holding back – she is choosing to trust him (1).",
  "She is extremely high / far away (1); tiny and fragile, as if about to vanish completely (1).",
  "It creates a shocking pause / emphasises Khalid’s sudden failure (1); it builds tension and slows the moment down (1).",
  "Any two: the falcon was expensive; his uncle spent years training her; he blames himself for losing her in a single afternoon; he fears disappointing his uncle (1 each).",
  "Up to 4: he stays calm and quiet, not angry (1); he seems curious – he may have expected this or trusted the bird (1); he encourages Khalid to persevere (1); his final comment reveals it was a test of commitment and that the bond depends on trust and not giving up; his first smile shows pride in Khalid (1).",
 ],
 Q2a=("According to Text B, what are the benefits of trees in cities?", [
  "they provide shade / make streets cooler",
  "they help cities cope with rising temperatures",
  "they filter dust and pollution from the air",
  "roots absorb rainwater and reduce flooding",
  "they provide homes and food for birds and insects",
  "they create corridors for wildlife through cities",
  "they reduce traffic noise",
  "green streets are linked to lower stress / better mental health",
  "hospital patients with a view of trees may recover faster",
  "children near green spaces are more active",
  "people want to walk, shop and spend time on tree-lined streets",
  "homes and businesses on them are often worth more",
  "their value increases as they grow",
 ]),
 Q2b=("What is the writer’s attitude towards the way many cities treat trees? Explain how you can tell.", [
  "Critical / frustrated: “Too often, the opposite happens.”",
  "Strongly disapproving: calls cutting mature trees “short-sighted in the extreme”.",
  "Scornful of token planting: “thin saplings that will take decades” and trees “added as decoration… if the budget allows”.",
  "Fair but firm: admits “there are real challenges”, yet insists “all of them can be solved with good planning”.",
  "Approving of cities that act: “Some cities are showing the way.”",
 ]),
 Q3s=[
  ("Using your own words, explain what the following words mean as they are used in the text:<br>(i) <b>bewildered</b> (paragraph 3)", 2),
  ("(ii) <b>undeterred</b> (paragraph 4)", 2),
  ("Re-read paragraph 2. How does the writer feel during the two hours of waiting? Refer to <b>two</b> details.", 2),
  ("Re-read paragraph 4. Why does Salma shake her head, and what does this suggest about her attitude to nature?", 2),
  ("Re-read paragraph 6. What does the writer mean by “with every chance of failure and no hesitation at all”?", 2),
 ],
 Q3s_ms=[
  "Confused / puzzled / disorientated (2). Award 1 for “surprised”.",
  "Not discouraged / not put off; carrying on despite obstacles (2). Award 1 for “brave”.",
  "Bored / impatient / doubtful – wonders whether the night will be “a disappointment” (1); startled / nervous – nearly screams when the crab scuttles across the foot (1).",
  "To stop the writer from interfering / trying to save the hatchling (1); she believes nature should take its course / observers must respect natural processes (1).",
  "Most hatchlings are likely to die (1), yet they set out immediately and bravely – the writer admires their courage (1).",
 ],
 Q3l=("Re-read paragraphs 3 and 4. Explain how the writer uses language to convey the hatchlings’ emergence and their struggle to reach the sea.", [
  ("Paragraph 3", [
   "“the sand… began to move. It trembled, sank a little, and suddenly erupted” – a sequence of verbs builds to a dramatic, volcanic moment.",
   "“boiling up out of the ground” – energetic, bubbling, uncontainable movement; sheer numbers.",
   "“scrambling over one another, flippers flailing” – frantic, clumsy urgency; alliteration mimics rapid movement.",
   "“no bigger than the palm of my hand” – tiny and vulnerable.",
   "“paused for a heartbeat… as if bewildered by the world” – a tender, human moment of uncertainty.",
   "“all together, they turned towards the sea” – sudden unity and purpose, almost instinctive and mysterious.",
  ]),
  ("Paragraph 4", [
   "“must have seemed endless” – the writer imagines the journey from their point of view; scale reversed.",
   "“tumbled… struggled out again” – repeated setbacks; relentless effort.",
   "“ridges no higher than a pencil” – precise, small image stressing how fragile they are.",
   "“desperate, furious effort” – intense, emotive adjectives give the hatchlings determination and personality.",
   "“A ghost crab darted from the shadows and seized one” – sudden predator; the danger is real and brutal.",
   "“drawn… as if pulled by an invisible thread” – instinct presented as a mysterious, irresistible force.",
  ]),
 ]),
 Q4=("Imagine you are the writer of Text C. You have been asked to give a speech to your school’s environment club about your night on the beach. Write the speech.",
  ["describe what happened on the beach, from the long wait to the hatchlings reaching the sea",
   "explain what you learned from Salma about turtles and how to observe wildlife",
   "persuade club members that experiences like this are worth their time, and suggest how they could get involved."],
  "speech",
  [("Bullet 1", "Meeting at nine in darkness; the sea as “breathing”; no torches; two hours of waiting; warm sand, stars, a crab; doubts; the sand trembling and erupting; dozens of tiny hatchlings; the struggle across thirty metres of sand; footprints, ridges, being flipped over; the ghost crab; reaching the waves and disappearing."),
   ("Bullet 2", "Light confuses turtles, so observers must use no torches; move slowly, speak softly, follow the guide; watch but don’t interfere, even when a predator strikes; only around one in a thousand survive to adulthood."),
   ("Bullet 3 (development – best answers go beyond the text sensibly)", "The experience was unforgettable and taught courage and respect for nature; patience is rewarded; club members could volunteer with conservation groups, follow the rules for observing wildlife, or raise awareness – suggestions should grow from the text.")]),
),
# ───────────────────────────── SET 6 ─────────────────────────────
dict(
 n=6, theme="Belonging and Learning",
 A=dict(title="The New Girl", kind="Fiction", paras=[
  "On her first day at the new school, Mei learned eleven words of English and forgot ten of them before lunch.",
  "The one she kept was ‘sorry’. She said it when she walked into the wrong classroom, when she dropped her tray in the canteen, and when a tall boy with a football under his arm bumped into her in the corridor and it was clearly his fault. ‘Sorry,’ she said, and he looked at her strangely and walked on.",
  "In lessons, the words poured over her like water over a stone. She could catch the shape of them – the rise of a question, the teacher’s patient pauses – but never the meaning. She copied everything from the board in careful, beautiful handwriting that she could not read, and at the end of each lesson she closed her book with a feeling that was worse than sadness: the feeling of being invisible.",
  "At home she did not tell her parents. Her father had moved the whole family across the world for this job, and her mother came home each evening with shadows under her eyes from her own long days of not understanding. So when they asked, Mei said school was fine, and went to her room and drew.",
  "She drew what she missed: the crowded market near her grandmother’s flat, the steam rising from the noodle stalls, the old men playing chess under the plane trees. She drew until the ache in her chest loosened a little. Then she hid the drawings in a folder under her bed.",
  "On the third Thursday, the art teacher, Mr Okoro, set the class a task. He wrote a single word on the board – HOME – and drew a question mark beside it. Mei understood that.",
  "For forty minutes she did not look up. When Mr Okoro stopped beside her desk, she flinched, ready to say sorry. But he said nothing. He simply stood there, looking at the market she had drawn – every lantern, every wrinkled face, the rising steam – and then, very quietly, he called the class over.",
  "Twenty students gathered round her desk. Mei’s face burned. She waited for laughter.",
  "Instead, the tall boy with the football leaned closer. ‘Is that real?’ he asked slowly, and when she did not understand, he pointed at the picture, then at her, and raised his eyebrows.",
  "Mei nodded. ‘Home,’ she said. It was the second English word she had kept.",
  "The boy grinned. ‘Can you draw me?’ he said, and mimed holding a pencil. A girl beside him laughed and said, ‘Me too!’",
  "By the end of the week, Mei had drawn eleven portraits, and she knew eleven names. She did not say sorry once.",
 ]),
 B=dict(title="Why Every Student Should Learn Another Language", kind="Newspaper opinion column", paras=[
  "In an age of instant translation apps, it is tempting to ask whether learning a foreign language is still worth the effort. Why spend years memorising verbs when your phone can translate a menu in seconds? More and more schools seem to agree: in many countries, the number of students studying languages has fallen sharply, and some schools have cut language lessons altogether.",
  "This is a mistake, and the evidence against it is growing. Research suggests that learning a second language strengthens the brain in ways that go far beyond vocabulary. Bilingual people often perform better on tasks that involve switching attention, solving problems and ignoring distractions – perhaps because their brains are constantly practising the skill of choosing between two languages. Some studies have even suggested that speaking more than one language may help to delay the effects of ageing on memory.",
  "Languages also open doors. Employers in international businesses value staff who can build relationships with clients in their own language, and many jobs in tourism, diplomacy, trade and healthcare depend on it. A translation app can convert words, but it cannot build trust, understand a joke or notice the polite hesitation that really means ‘no’.",
  "Perhaps most importantly, learning a language changes how we see other people. To learn a language is to discover that there are other ways of organising the world: words for feelings your own language has no name for, different ways of showing respect, different ideas about time. Students who struggle to order a meal in another language also learn, from the inside, what it feels like to be a newcomer – an experience that tends to make people more patient and more understanding.",
  "None of this means that learning a language is easy. It demands time, patience and a willingness to make mistakes in public, which many teenagers find excruciating. Schools also struggle to recruit qualified language teachers. But these are reasons to support language learning better, not to abandon it.",
  "A translation app is a useful tool. It is not a substitute for the human effort of understanding someone in their own words. If schools give up on languages, they will produce a generation that can read the world through a screen, but not speak to it.",
 ]),
 C=dict(title="Learning to Swim at Thirty-One", kind="Autobiographical writing", paras=[
  "I was thirty-one years old the first time I put my face in the water on purpose. I had spent my whole life avoiding it. As a child I had sat at the edge of swimming pools with a book, pretending to be busy; as an adult I had become an expert in excuses – a cold, a cut on my foot, a sudden urgent phone call. Nobody, I think, ever guessed the truth: that water terrified me.",
  "The adult beginners’ class met on Tuesday evenings at the local pool. There were six of us: a retired bus driver, two sisters in their forties, a young father who wanted to be able to swim with his daughter, a nervous accountant, and me. Our instructor, Joanna, was about twenty-five and had the <b>unflappable</b> calm of someone who has taught a great many frightened people.",
  "The first lesson was <b>humiliating</b>. We stood in water up to our waists, gripping the side like shipwreck survivors, while children in the next lane flashed past like fish. Joanna asked us to blow bubbles. That was all – just to lower our mouths to the surface and breathe out. I could not do it. Every time the water touched my chin, some ancient alarm inside me began to shriek, and I jerked my head back, gasping, my heart hammering against my ribs as though I had been dragged from the sea.",
  "Joanna did not push. She simply waited, week after week, as I edged closer. Bubbles. Then my nose. Then, one extraordinary Tuesday in the fourth week, my whole face, eyes screwed shut, for a count of three. When I came up, the whole class was clapping, and the retired bus driver had tears in his eyes. I realised then that every one of us was fighting the same private battle.",
  "It took me eleven weeks to swim a single width of the pool. It was the slowest, clumsiest, least elegant width anyone has ever swum, all splashing arms and panicked kicking, and when my hand finally slapped the far wall I let out a shout of triumph that echoed round the building and made a lifeguard look up in alarm.",
  "I am not a good swimmer, even now. But I no longer sit at the edge with a book. I have learned something more useful than swimming: that fear is not a wall but a door, and that it opens, very slowly, from the inside. It is never too late to learn – it only feels that way.",
 ]),
 Q1=[
  ("Which English word does Mei keep from her first day?", 1),
  ("Give <b>two</b> situations in which Mei says ‘sorry’.", 2),
  ("Why do you think the boy in the corridor looks at Mei “strangely”?", 2),
  ("Explain what the writer suggests by comparing the words in lessons to “water over a stone”.", 2),
  ("Using your own words, explain why Mei does not tell her parents how she feels.", 3),
  ("Re-read paragraph 5. What do Mei’s drawings reveal about her feelings?", 2),
  ("Why does Mei “flinch” when Mr Okoro stops beside her desk?", 2),
  ("“Mei’s face burned. She waited for laughter.” What does this suggest about Mei at this moment?", 2),
  ("How has Mei’s situation changed by the end of the story? Refer closely to the final paragraph.", 4),
 ],
 Q1_ms=[
  "‘Sorry’ (1).",
  "Any two: walking into the wrong classroom; dropping her tray in the canteen; when the boy bumped into her (1 each).",
  "It was his fault, so her apology is unexpected / unnecessary (1); he may not understand her, or find her behaviour odd (1).",
  "The words flow past her without being absorbed / understood (1); she is surrounded by language but it leaves no meaning – she stays shut out (1).",
  "Up to 3: her father moved the family for his job, so she does not want him to feel guilty (1); her mother is exhausted and struggling herself (1); Mei wants to protect them / not add to their worries (1).",
  "She is homesick / misses her grandmother and her old life (1); drawing comforts her and eases her pain (1).",
  "She expects to be told off / to be in trouble (1); she is anxious and used to apologising (1).",
  "She is embarrassed / self-conscious (1); she expects to be mocked, showing her low confidence (1).",
  "Up to 4: she has gone from feeling invisible to being noticed and valued (1); art has become a way to communicate across the language barrier (1); she has made connections – eleven names echoes the eleven words of the opening (1); she no longer says sorry, showing new confidence and belonging (1).",
 ],
 Q2a=("According to Text B, what are the benefits of learning another language?", [
  "strengthens the brain beyond vocabulary",
  "better at switching attention",
  "better at solving problems",
  "better at ignoring distractions",
  "may delay the effects of ageing on memory",
  "valued by employers in international business",
  "needed for jobs in tourism, diplomacy, trade and healthcare",
  "helps build relationships / trust with people",
  "helps you understand humour and unspoken meanings",
  "shows other ways of organising the world / other cultures",
  "teaches what it is like to be a newcomer",
  "makes people more patient and understanding",
 ]),
 Q2b=("What is the writer’s attitude towards schools that cut language lessons? Explain how you can tell.", [
  "Strongly critical: “This is a mistake.”",
  "Confident that evidence is on their side: “the evidence against it is growing”.",
  "Dismissive of the translation-app argument: “not a substitute for the human effort”.",
  "Fair about the difficulties but firm: they are “reasons to support language learning better, not to abandon it”.",
  "Warning of serious consequences: a generation that can “read the world through a screen, but not speak to it”.",
 ]),
 Q3s=[
  ("Using your own words, explain what the following words mean as they are used in the text:<br>(i) <b>unflappable</b> (paragraph 2)", 2),
  ("(ii) <b>humiliating</b> (paragraph 3)", 2),
  ("Re-read paragraph 1. What do the writer’s excuses suggest about how the writer felt about this fear?", 2),
  ("Re-read paragraph 3. What does the comparison “like shipwreck survivors” suggest?", 2),
  ("Re-read paragraph 4. What did the writer realise when the class clapped?", 2),
 ],
 Q3s_ms=[
  "Calm under pressure / never flustered or agitated (2). Award 1 for “calm” alone.",
  "Deeply embarrassing / making one feel foolish or ashamed (2). Award 1 for “hard”.",
  "The writer was ashamed / embarrassed of the fear (1) and kept it secret by hiding it carefully (1).",
  "They clung on desperately / felt in danger (1); humorous exaggeration of their helplessness and fear (1).",
  "Everyone in the class shared similar fears / private struggles (1); they supported one another – a sense of solidarity (1).",
 ],
 Q3l=("Re-read paragraphs 3 and 5. Explain how the writer uses language to convey the writer’s fear at the start and triumph at the end.", [
  ("Paragraph 3", [
   "“humiliating” – strong opening judgement; shame as much as fear.",
   "“gripping the side like shipwreck survivors” – desperate, life-or-death image, comically exaggerated for waist-deep water.",
   "“children… flashed past like fish” – contrast: effortless, natural ease against the adults’ struggle.",
   "“That was all” – short sentence stresses how small the task was, making the failure more painful.",
   "“some ancient alarm inside me began to shriek” – fear as primitive, uncontrollable and loud.",
   "“heart hammering… as though I had been dragged from the sea” – violent physical reaction; panic out of proportion.",
  ]),
  ("Paragraph 5", [
   "“eleven weeks… a single width” – contrast between long effort and small distance; humour and honesty.",
   "“slowest, clumsiest, least elegant” – list of superlatives, self-mocking and warm.",
   "“all splashing arms and panicked kicking” – lively, chaotic movement; fear still present.",
   "“my hand finally slapped the far wall” – “finally” and the sharp verb mark the moment of achievement.",
   "“a shout of triumph that echoed round the building” – joy too big to contain; filling the space that once frightened.",
   "“made a lifeguard look up in alarm” – humorous ending; triumph mistaken for danger.",
  ]),
 ]),
 Q4=("Imagine you are the writer of Text C. A community magazine has asked you to write an article encouraging adults to learn a new skill, based on your experience of learning to swim. Write the article.",
  ["describe your fear of water and what the early lessons were like",
   "explain what helped you to make progress",
   "persuade readers that it is never too late to learn something new."],
  "article",
  [("Bullet 1", "A lifelong fear hidden behind excuses; sitting with a book at the pool edge; the adult class of six; the humiliating first lesson – gripping the side, children flashing past, unable to blow bubbles, panic and a racing heart."),
   ("Bullet 2", "Joanna’s patience and calm – she did not push; small steps (bubbles, nose, whole face); the class’s support and clapping; realising everyone shared the same struggle; persistence over eleven weeks."),
   ("Bullet 3 (persuasion – best answers develop this)", "Progress matters more than perfection (“not a good swimmer, even now”); fear is “a door, not a wall”; the joy of the triumph; others in the class (a father, a retired driver) show that anyone can start; practical encouragement – find a patient teacher, take small steps, learn with others.")]),
),
]
