"""Content for the IGCSE 0500 Paper 1 Practice Pack. All texts are original."""

SETS = [
# ───────────────────────────── SET 1 ─────────────────────────────
dict(
 n=1, theme="The Sea",
 A=dict(title="The Last Pearl", kind="Fiction", paras=[
  "Salem had imagined this morning so many times that the real thing felt slightly wrong, like a photograph printed in the wrong colours. The sea was not the bright blue of his daydreams but a flat, milky green, and the dhow smelled of diesel and old rope rather than adventure.",
  "His grandfather sat at the stern, one hand resting on the tiller as lightly as if it were a sleeping cat. Jaddi had not dived for pearls in fifty years, but he still read the water the way other men read newspapers, frowning at a ripple here, nodding at a darker patch there.",
  "“Here,” he said at last, and cut the engine.",
  "The silence arrived all at once. Salem could hear the hull creak and the slap of small waves and, somewhere beneath it all, his own heart, which seemed to have climbed into his throat.",
  "“You don’t have to,” Jaddi said, without looking at him.",
  "“I want to.” It came out louder than Salem intended.",
  "His grandfather handed him a nose clip carved from turtle shell – the same one, he said, that he had worn as a boy – and a stone tied to a length of rope. “The stone takes you down. The rope brings you back. Your job is only to keep your eyes open.”",
  "Salem clipped his nose, filled his lungs and let the stone pull him under.",
  "For the first few seconds it was wonderful. The noise of the world switched off. Sunlight fell through the water in long, trembling ribbons, and the seabed rose to meet him, scattered with shells and the slow grey shapes of oysters. Then the pressure began to squeeze his ears, a voice inside him began to count, faster and faster, and suddenly the whole weight of the Gulf seemed to be pressing on his chest.",
  "He tugged the rope twice, as he had been taught, and kicked frantically for the light.",
  "He broke the surface gasping, eyes stinging, certain he had failed. But his grandfather was leaning over the side, and he was laughing – not unkindly, but with a kind of delight Salem had never seen on his face.",
  "“Four metres,” Jaddi said. “The first time I went down, I reached two, and I cried for my mother.” He reached out a hand, rough as rope. “Again tomorrow?”",
  "Salem looked at the water, which no longer seemed flat or ordinary. “Again tomorrow,” he said.",
 ]),
 B=dict(title="The Quiet Crisis Beneath the Waves", kind="Magazine article", paras=[
  "Coral reefs cover less than one per cent of the ocean floor, yet they are home to around a quarter of all marine species. Divers often describe them as underwater cities and, like cities, they are busy, crowded and surprisingly fragile.",
  "The greatest threat is heat. When the sea stays too warm for too long, corals expel the tiny algae that live inside them and give them both their colour and most of their food. The coral turns white – ‘bleached’ – and, if the water does not cool, it slowly starves. Some reefs in the Gulf, which already survive in some of the hottest seas on Earth, have lost large areas of coral during recent summers.",
  "Heat is not the only problem. As the ocean absorbs more carbon dioxide from the air, it becomes more acidic, which makes it harder for corals to build their stony skeletons. Closer to shore, construction and dredging stir up sediment that blocks the light corals need. Fertiliser washed off farmland feeds algae that smother reefs, while careless anchoring and overfishing upset the delicate balance of life that keeps a reef healthy. Even sunscreen, in popular bays, may add to the stress.",
  "It would be easy to give up. Yet scientists and volunteers are refusing to do so. In nurseries on the seabed, fragments of healthy coral are grown on frames like seedlings in a garden and then replanted on damaged reefs. Researchers are breeding corals that can tolerate warmer water. Marine protected areas, where fishing and anchoring are restricted, give reefs time to recover, and in several of them fish numbers have risen sharply within a few years.",
  "Some of the most important work is also the least glamorous. Every week, volunteer divers count fish, photograph coral and record which colonies have bleached. Their patient, unpaid data allows scientists to spot problems early. Many of these volunteers are ordinary office workers and students who simply cannot bear to watch something beautiful disappear. They are, in their quiet way, heroes.",
  "None of this will be enough on its own. Unless the world cuts the emissions that are heating the oceans, reefs will keep bleaching faster than they can be repaired. But the people rebuilding them, fragment by fragment, are buying precious time – and reminding the rest of us that what has been damaged can still be saved.",
 ]),
 C=dict(title="Crossing to Musandam", kind="Travel memoir", paras=[
  "We left Dibba just after dawn, when the sea was so <b>placid</b> that the ferry seemed to be sliding across a sheet of polished pewter. The mountains of Musandam rose ahead of us, brown and bare and folded like crumpled paper, and my brother Karim, who had planned the whole trip, stood at the rail naming every headland as if he had built it himself.",
  "The change came without warning. One moment the horizon was a clean, sharp line; the next it had vanished behind a bruised purple wall of cloud that swallowed the mountains one by one. The wind arrived first, snatching Karim’s cap and flinging it into the wake. Then the sea itself woke up. Waves that had been lazy ripples reared into grey, white-crested ridges, and the ferry began to climb each one with a groan, hang for a sickening second at the top, and then plunge into the trough beyond.",
  "Inside the cabin, bags slid across the floor. A tray of tea glasses lurched off the counter and exploded like fireworks. An elderly woman beside me closed her eyes and moved her lips silently, and a small boy stopped crying and simply stared, which was somehow worse.",
  "Through the salt-streaked window, the world had turned to chaos. Rain came sideways, hammering the glass like a thousand impatient fists. Spray burst over the bow in great white explosions, and each time the ferry buried its nose in a wave, the whole vessel shuddered as though it had been struck. Only the captain seemed unmoved. I could see him on the bridge above us, his hands steady on the wheel, staring <b>resolutely</b> ahead as if the storm were an argument he fully intended to win.",
  "It lasted perhaps forty minutes. Then, as suddenly as it had come, the cloud tore open and a shaft of sunlight fell across the water like a spotlight on a stage. The waves sank back into a gentle swell. Someone began to laugh with relief, and soon the whole cabin was laughing – at the broken glasses, at our soaked clothes, at Karim, who had lost not only his cap but, for once, his voice.",
  "We reached Khasab two hours late. As the ferry nosed into the harbour, I noticed the captain step out onto the deck and pour himself a glass of water with hands that, now it was over, were trembling. I have thought about those hands many times since. The storm had been humbling: it reminded us how little we control, and how much we depend on the calm courage of strangers.",
 ]),
 Q1=[
  ("Give <b>two</b> ways in which the real morning was different from Salem’s daydreams.", 2),
  ("Re-read paragraph 2.<br>(i) What does the comparison “as lightly as if it were a sleeping cat” suggest about how Jaddi steers the boat?", 2),
  ("(ii) Explain what the writer means by “he still read the water the way other men read newspapers”.", 2),
  ("How does Salem feel when the engine is cut? Support your answer with a detail from the text.", 2),
  ("“It came out louder than Salem intended.” What does this suggest about Salem at this moment?", 2),
  ("Why do you think the nose clip is important to Jaddi?", 2),
  ("Using your own words, explain what Jaddi tells Salem his only job is, and why he only has one job.", 2),
  ("Re-read paragraph 9 (“For the first few seconds…”). Explain how Salem’s experience changes during the dive.", 3),
  ("Why does Salem feel “certain he had failed”, and why is he wrong? Use your own words.", 3),
 ],
 Q1_ms=[
  "Any two: the sea was not bright blue but <i>milky green</i> (1); it was <i>flat</i> / not exciting (1); the dhow smelled of <i>diesel and old rope</i>, not adventure (1).",
  "He steers gently / with little effort (1); he is relaxed, calm or confident, so steering comes naturally from experience (1).",
  "He can still understand / interpret the sea easily (1), because of long experience; he reads signs in the water such as ripples and colour as naturally as an everyday habit (1).",
  "Nervous / frightened / tense (1) + evidence: his heart “seemed to have climbed into his throat” (1).",
  "He is trying to sound braver or more certain than he feels (1); he may be trying to convince himself / prove himself to his grandfather (1).",
  "It is a link to his own past as a diver / he wore it as a boy (1); passing it on shows pride, trust or a wish to continue the family tradition (1).",
  "His only job is to keep looking / stay alert / observe (1); the stone and rope do the work of taking him down and bringing him back (1).",
  "Up to 3: at first peaceful and amazing – the noise stops, beautiful light and seabed (1); then physical discomfort – pressure squeezes his ears (1); then rising panic – counting faster, feels crushed / overwhelmed by the weight of water (1).",
  "Up to 3: he panicked / came up early / surfaced gasping (1); but his grandfather is delighted / laughing with pleasure (1); four metres is further than his grandfather’s first dive of two metres / he is invited to dive again, showing approval (1).",
 ],
 Q2a=("According to Text B, what threatens coral reefs <b>and</b> what is being done to protect them?", [
  "sea temperatures stay too high for too long",
  "corals lose / expel the algae that give colour and food, so they bleach",
  "bleached corals starve if the water stays warm",
  "carbon dioxide makes the ocean more acidic",
  "acidity makes it harder for corals to build skeletons",
  "coastal building / dredging creates sediment that blocks light",
  "fertiliser run-off feeds algae that smother reefs",
  "careless anchoring damages reefs",
  "overfishing upsets the reef’s balance",
  "sunscreen may add stress in busy bays",
  "coral fragments grown in underwater nurseries and replanted",
  "breeding corals that tolerate heat",
  "protected areas limit fishing and anchoring so reefs recover",
  "volunteers monitor / record reef health so problems are spotted early",
  "(ultimately) the world needs to cut emissions",
 ]),
 Q2b=("What is the writer’s attitude towards the volunteers who help protect reefs? Explain how you can tell.", [
  "Admiring / sees them as heroic: “They are, in their quiet way, heroes.”",
  "Respects their dedication: their work is “patient” and “unpaid”.",
  "Values their importance: “some of the most important work”, allowing problems to be spotted early.",
  "Sympathetic / shares their feelings: they “cannot bear to watch something beautiful disappear”.",
  "Hopeful because of them: they are “buying precious time”.",
 ]),
 Q3s=[
  ("Using your own words, explain what the following words mean as they are used in the text:<br>(i) <b>placid</b> (paragraph 1)", 2),
  ("(ii) <b>resolutely</b> (paragraph 4)", 2),
  ("Re-read paragraph 1. What impression does the writer give of Karim? Refer to <b>two</b> details.", 2),
  ("Re-read paragraph 3. Why does the writer think the small boy’s silence “was somehow worse” than his crying?", 2),
  ("Re-read paragraph 6. What do the captain’s trembling hands reveal about him?", 2),
 ],
 Q3s_ms=[
  "Calm / still / undisturbed / peaceful (2). Award 1 for a partial meaning, e.g. “quiet”.",
  "Determinedly / firmly / with unwavering purpose (2). Award 1 for “bravely” or “seriously”.",
  "Enthusiastic / proud / a bit of a know-it-all (1) + detail: he planned the whole trip; he named every headland “as if he had built it himself” (1).",
  "Silence suggests shock or terror too deep for tears (1); it makes the danger feel real / unsettles the adults (1).",
  "He had been frightened too but hid it (1); his calm was courage / self-control rather than an absence of fear (1).",
 ],
 Q3l=("Re-read paragraphs 2 and 4. Explain how the writer uses language to convey the power of the storm and people’s reactions to it.", [
  ("Paragraph 2", [
   "“without warning” / “one moment… the next” – suddenness, no time to prepare.",
   "“bruised purple wall of cloud” – “bruised” suggests injury / violence; “wall” – solid, impassable, trapping.",
   "“swallowed the mountains one by one” – the storm as a monster devouring even huge, solid things.",
   "“snatching… flinging” – aggressive, careless verbs; the wind as a thief or bully.",
   "“the sea itself woke up” – personified; a sleeping giant becoming dangerous.",
   "“reared” – like a wild animal / horse; “climb… hang for a sickening second… plunge” – rhythm mimics the ferry’s motion and the stomach-lurching fear.",
  ]),
  ("Paragraph 4", [
   "“the world had turned to chaos” – total loss of order and control.",
   "“hammering the glass like a thousand impatient fists” – relentless, violent, as if trying to break in; the passengers feel besieged.",
   "“great white explosions” – continues the language of violence and war.",
   "“buried its nose” / “shuddered as though it had been struck” – the ferry as a wounded living thing; fragility against the storm.",
   "“Only the captain seemed unmoved… steady… resolutely” – contrast; his stillness highlights the chaos and reassures.",
   "“an argument he fully intended to win” – the storm as an opponent; the captain’s quiet, stubborn confidence.",
  ]),
 ]),
 Q4=("Imagine you are Karim. That evening in Khasab you write a letter to a friend about the journey.",
  ["describe the journey before and during the storm",
   "explain how the other passengers and the captain behaved",
   "reflect on what you learned about yourself and other people from the experience."],
  "letter",
  [("Bullet 1", "Calm start – smooth, silvery sea; bare mountains; Karim’s pride in the trip he planned and enjoyment of naming headlands; sudden purple cloud; cap snatched by the wind; huge waves, the ferry climbing and plunging; rain, spray, shuddering."),
   ("Bullet 2", "Bags sliding, glasses smashing; the elderly woman praying silently with eyes closed; the boy falling silent and staring; the captain steady, determined, apparently unmoved; relief and laughter afterwards; the captain’s trembling hands at Khasab."),
   ("Bullet 3 (inference – best answers develop this)", "Karim was lost for words – perhaps humbled or embarrassed after being so confident; he may feel responsible for planning the trip; realises how little control people have; admires the captain’s hidden fear and courage; values his sibling / the shared laughter; may see humour in losing his cap and his voice.")]),
),
# ───────────────────────────── SET 2 ─────────────────────────────
dict(
 n=2, theme="Work and Challenge",
 A=dict(title="Service", kind="Fiction", paras=[
  "Maya had been warned that the kitchen would be hot. Nobody had warned her that it would be loud.",
  "At seven o’clock, when the first orders began to arrive, the room seemed to explode. Pans hissed and spat. A printer at the end of the counter chattered out tickets in an endless paper tongue. Somewhere a timer shrieked and was ignored, and above it all rose the voice of Chef Idris, calling out orders in a rhythm so fast and so precise that it sounded less like speech than like drumming.",
  "“Two lamb, one bream, one risotto – Maya, where are my herbs?”",
  "Her herbs. She looked down at the board in front of her, at the small green mountain of parsley she had been chopping for twenty minutes, and realised with horror that it was still a mountain. The other cooks moved around her like dancers who had rehearsed the same routine a thousand times, pivoting, reaching, sliding plates along the counter without once looking up. Maya felt like someone who had wandered onto the stage in the middle of a performance.",
  "“Faster,” said Tomas, the sous-chef, as he passed. It was not unkind; it was simply a fact.",
  "She tried. She rocked the knife the way she had seen in videos and felt the blade skid dangerously close to her knuckles. Her face burned. For a terrible moment she thought she might cry, there, in front of everyone, and she could imagine exactly how the story would be told the next day: the new girl who lasted one hour.",
  "Then Idris was beside her. He did not raise his voice. He simply took her hand, curled her fingertips under like a claw, and guided the knife in three slow, even strokes. “Speed comes from calm,” he said. “Not the other way round.” And he was gone again, back to his drumming.",
  "By ten o’clock her feet ached, her apron was stained green and she had burned her wrist on the edge of a tray. But the herbs had arrived on every plate. When the last ticket was finally speared on the spike, the cooks leaned against the counters and someone passed round bottles of cold water. Tomas lifted his towards her in a small salute.",
  "Maya had never been so tired. She had never, she realised, been so happy.",
 ]),
 B=dict(title="Why the Pen Is Making a Comeback", kind="Newspaper feature", paras=[
  "A generation ago, experts predicted that handwriting would soon be as old-fashioned as the typewriter. Schools were buying tablets, offices were going ‘paperless’, and it seemed obvious that the keyboard had won. Yet walk into any stationery shop today and you will find shelves of expensive notebooks, fountain pens and planners, many of them bought by people under thirty.",
  "Part of the reason is scientific. Several studies have suggested that students who take notes by hand remember more than those who type. Typing is so fast that it tempts us to record lectures word for word, without thinking. Writing by hand is slower, so we are forced to choose what matters and put it into our own words – and that act of choosing is exactly what fixes information in the memory. Brain-imaging research also suggests that forming letters by hand activates areas of the brain linked to learning more strongly than pressing keys does.",
  "There are other benefits, too. A notebook has no notifications. It will not tempt you to check the news, reply to a message or watch ‘just one’ video. For a generation that spends many hours a day on screens, a sheet of paper can feel like a small, quiet room with the door closed. Many people also say that writing by hand helps them think more creatively: the freedom to doodle, draw arrows and scribble in the margins encourages connections that a neat, linear document does not.",
  "And then there is the simple pleasure of it. A handwritten page is personal in a way that a typed one never is. Our handwriting carries our mood – hurried, careful, excited – and a handwritten letter still means more to most people than an email ever could.",
  "None of this means we should abandon our laptops. Typing is faster, easier to edit and easier to share, and for many tasks it is clearly the better tool. Some people also find handwriting physically difficult, and technology has opened doors for them that should never be closed. But the idea that the pen is finished now looks rather foolish. Perhaps the future is not paper or screen, but knowing when to use each.",
 ]),
 C=dict(title="The Dune", kind="Autobiographical writing", paras=[
  "Our guide, Rashid, woke us at four. The camp was still in darkness, and the cold took me by surprise: I had packed for the desert I had seen in films, not for this sharp, <b>penetrating</b> chill that crept through two jumpers and settled in my bones. We drank sweet tea in silence, then followed the small bobbing circle of Rashid’s torch towards the foot of the dune.",
  "In the gloom it looked like a mountain. It rose above us in a single, immense curve, its crest sharp as a blade against the fading stars. Rashid said it was over a hundred metres high. He said it cheerfully, as though that were good news.",
  "The first twenty steps were easy. Then the sand began to fight back. Every time I pushed forward, the slope collapsed beneath my feet and slid me gently back, so that I seemed to be climbing a staircase that was quietly being dismantled beneath me. My thighs burned. My breath came in ragged gasps that tore at my throat, and the crest, whenever I dared to look up, seemed no closer than before. Beside me, my friend Lena had stopped talking altogether, which in eleven years of friendship I had never known to happen.",
  "Rashid, meanwhile, moved up the slope with maddening ease, placing his bare feet in the firmer sand along the ridge and pausing now and then to wait for us with the patience of someone who has seen hundreds of tourists do exactly this. “Don’t look at the top,” he advised. “Look at your next step. The top will come.” It was, I thought <b>grudgingly</b>, the most irritating advice I had ever received, and also the only thing that worked.",
  "We reached the crest just as the sun did. For a long moment none of us spoke. Below us the desert unrolled in every direction, an ocean of sand frozen in mid-storm, wave after golden wave of it, each crest lit with fire and each hollow still drowned in violet shadow. As the light climbed, the colours shifted from rose to copper to gold, and the shadows shrank back into the dunes like water draining from a basin. The silence was total – not the silence of an empty room, but something vast and living, as if the whole landscape were holding its breath.",
  "Lena found her voice first. “Was it worth it?” she asked, and we both laughed, because the question was ridiculous. I have climbed higher things since, but I have never forgotten Rashid’s advice. When a task seems impossibly large, I still hear him: look at your next step. The top will come.",
 ]),
 Q1=[
  ("What had Maya <b>not</b> been warned about?", 1),
  ("Re-read paragraph 2. Give <b>two</b> examples of noise in the kitchen.", 2),
  ("Explain what the writer suggests by comparing Chef Idris’s voice to “drumming”.", 2),
  ("Why does Maya feel “horror” when she looks at the herbs?", 2),
  ("Using your own words, explain how the other cooks move, and why this makes Maya feel like an outsider.", 3),
  ("“It was not unkind; it was simply a fact.” What does this suggest about Tomas and the kitchen?", 2),
  ("What does Maya fear will happen, and what does this show about her?", 2),
  ("How does Chef Idris help Maya, and what does his advice mean? Use your own words.", 3),
  ("Explain why Maya feels happy at the end, even though she is exhausted.", 3),
 ],
 Q1_ms=[
  "That it would be loud / the noise (1).",
  "Any two: pans hissing and spitting; the printer chattering; a timer shrieking; Chef Idris calling out orders (1 each).",
  "His orders are fast, regular and rhythmic (1); he sets the pace / controls everyone, like a drummer keeping a band in time (1).",
  "After twenty minutes she has barely made progress (1); the chef needs them now and she fears letting the team down / being exposed (1).",
  "Up to 3: they move smoothly / confidently / in a coordinated way (1); as if they have practised for a long time and do not need to look (1); Maya does not know the routine and feels out of place / in the way / conspicuous (1).",
  "Tomas is direct / focused on the work rather than feelings, but not hostile (1); the kitchen values speed and efficiency; there is no time for politeness (1).",
  "That she will cry in front of everyone and become a joke / “the new girl who lasted one hour” (1); she cares about proving herself / is self-conscious / afraid of failure (1).",
  "Up to 3: he helps calmly and quietly, without shouting (1); he physically shows her the safe technique (curled fingers, slow strokes) (1); advice: staying calm and controlled leads to speed; rushing causes mistakes (1).",
  "Up to 3: she succeeded – the herbs reached every plate (1); she is accepted by the team – shared water, Tomas’s salute (1); a sense of achievement from overcoming her fear / surviving a hard first night (1).",
 ],
 Q2a=("According to Text B, what are the benefits of writing by hand?", [
  "people who take notes by hand remember more",
  "it is slower, so you must select what is important",
  "you put information into your own words",
  "this process of choosing fixes it in the memory",
  "forming letters stimulates learning areas of the brain more strongly",
  "a notebook has no notifications / fewer distractions",
  "it offers a break from screens / a calm, private space",
  "it can help people think more creatively",
  "freedom to doodle, draw arrows and annotate encourages new connections",
  "it is enjoyable / a simple pleasure",
  "it is more personal – handwriting shows your mood",
  "handwritten letters are valued more than emails",
 ]),
 Q2b=("What is the writer’s attitude towards typing and technology? Explain how you can tell.", [
  "Balanced / not against technology: “None of this means we should abandon our laptops.”",
  "Recognises its strengths: typing is “faster, easier to edit and easier to share”, “clearly the better tool” for many tasks.",
  "Values its role in inclusion: it has “opened doors… that should never be closed”.",
  "Critical of its distractions: notifications, the temptation of “just one” video.",
  "Dismissive of predictions that it would replace handwriting: “now looks rather foolish”; favours using each appropriately.",
 ]),
 Q3s=[
  ("Using your own words, explain what the following words mean as they are used in the text:<br>(i) <b>penetrating</b> (paragraph 1)", 2),
  ("(ii) <b>grudgingly</b> (paragraph 4)", 2),
  ("Re-read paragraph 2. What does “He said it cheerfully, as though that were good news” suggest about the writer’s feelings?", 2),
  ("Re-read paragraph 3. Why is it significant that Lena “had stopped talking altogether”?", 2),
  ("Re-read paragraph 4. Why does the writer describe Rashid’s ease as “maddening”?", 2),
 ],
 Q3s_ms=[
  "Piercing / getting deep inside (through clothing) (2). Award 1 for “very cold” alone.",
  "Reluctantly / unwillingly, admitting something against one’s wishes (2). Award 1 for “annoyed”.",
  "The writer found the height daunting / worrying, not good news (1); humorous / ironic contrast with Rashid’s enthusiasm (1).",
  "Lena normally talks constantly / never stops (1); her silence shows how exhausted / how much she was struggling (1).",
  "His effortlessness contrasts with their painful struggle (1); this is frustrating / makes them envious or irritated (1).",
 ],
 Q3l=("Re-read paragraphs 3 and 5. Explain how the writer uses language to convey the difficulty of the climb and the beauty of the view from the top.", [
  ("Paragraph 3", [
   "“the sand began to fight back” – personification; the dune as an opponent resisting the climbers.",
   "“collapsed… slid me gently back” – the ground gives way; “gently” is ironic: effortless for the sand, exhausting for her.",
   "“a staircase that was quietly being dismantled beneath me” – progress constantly undone; frustrating, almost nightmarish.",
   "“My thighs burned” – short sentence; heat and pain; physical exhaustion.",
   "“ragged gasps that tore at my throat” – violent verb; breathing itself is painful.",
   "“seemed no closer than before” – hopelessness; the goal keeps retreating.",
  ]),
  ("Paragraph 5", [
   "“unrolled in every direction” – like a carpet or map; vast, spreading endlessly.",
   "“an ocean of sand frozen in mid-storm, wave after golden wave” – metaphor turns the desert into a sea; stillness and energy at once; repetition conveys scale.",
   "“lit with fire… drowned in violet shadow” – contrasting light and dark; rich, intense colour.",
   "“rose to copper to gold” – a list tracking changing colour; precious-metal connotations of value and wonder.",
   "“like water draining from a basin” – simile for the shadows shrinking; smooth, gradual movement.",
   "“something vast and living… holding its breath” – personification; awe, reverence, a sense of the sacred.",
  ]),
 ]),
 Q4=("Imagine you are Rashid, the guide. At the end of the season the tour company asks you to write a report about the dawn dune climb, to help train new guides.",
  ["describe what the climb is like and the challenges visitors face",
   "explain how guides can help visitors succeed, using examples from this group",
   "suggest what makes the experience worthwhile and how it could be improved."],
  "report",
  [("Bullet 1", "4 a.m. start in darkness; unexpected cold – visitors under-prepared; dune over 100 m; easy start then sand collapses underfoot; burning legs, gasping breath; the top never seems to get closer; even talkative visitors fall silent."),
   ("Bullet 2", "Wake visitors early with sweet tea; lead with a torch; walk on firmer sand along the ridge; pause and wait patiently; give simple advice – look at the next step, not the top; stay cheerful; understand visitors may feel irritated."),
   ("Bullet 3 (evaluation – best answers develop this)", "The sunrise view: colours, scale, silence; shared laughter and achievement; a lesson visitors remember for years. Improvements: warn guests to bring warm layers; prepare them for the difficulty; perhaps offer rest stops or a gentler route; recognise that a guide’s cheerfulness can seem “maddening”.")]),
),
# ───────────────────────────── SET 3 ─────────────────────────────
dict(
 n=3, theme="Endings and Beginnings",
 A=dict(title="The Last Show", kind="Fiction", paras=[
  "The Rex Cinema had been showing films on Harbour Street for sixty-two years, and tonight it would show its last.",
  "Mr Desai arrived at five, as he always did, three hours before the doors opened. He unlocked the side entrance with a key he had carried for forty years and climbed the narrow stairs to the projection room, his granddaughter Priya following with a box of sandwiches her mother had insisted on.",
  "The room was small and hot and smelled of dust and warm metal. The old projector stood in the centre like a great black animal asleep in its stall. The cinema had gone digital years ago, and a sleek grey machine now did the real work from a corner, but Mr Desai had asked the owners for one favour: that the final film be shown the old way, on the reels.",
  "Priya watched him thread the film. His fingers, usually so stiff that he struggled with buttons, moved with a sure, quiet grace, looping the film through a maze of wheels and gates without a single wasted movement. She realised she had never seen him do the thing he had done every night of her mother’s childhood.",
  "“What will you do,” she asked carefully, “after?”",
  "He shrugged. “Sleep, maybe. Your grandmother says I have forty years of evenings to give back to her.” He smiled, but he did not look up from the reel.",
  "At eight, the house lights dimmed. Through the small square window, Priya could see the audience – every seat filled, some people standing at the back. Many of them, she guessed, had had their first dates here, or brought their own children to Saturday matinees. Her grandfather pressed the switch and the projector woke with a steady, clattering purr. A beam of light leapt across the darkness, full of spinning dust, and on the screen far below the old film flickered into life.",
  "They did not watch the film. Priya watched her grandfather, and her grandfather watched the machine, listening to it the way a doctor listens to a heartbeat.",
  "When the credits rolled, the audience did not leave. Instead, one by one, they turned in their seats and looked up at the little window, and began to applaud. Mr Desai stood very still. Then, slowly, he raised one hand, and Priya saw that he was crying – and that he did not mind at all.",
 ]),
 B=dict(title="Why Teenagers Can’t Get to Sleep – and Why It Matters", kind="Online article", paras=[
  "Every morning, in homes around the world, the same battle takes place. Alarms ring, parents call, and teenagers who were wide awake at midnight lie in bed as if they have been drugged. It is tempting to blame laziness. The science suggests something rather different.",
  "During adolescence, the body clock shifts. The hormone melatonin, which makes us feel sleepy, is released around two hours later in teenagers than in younger children or adults. This means that many teenagers simply do not feel tired until eleven o’clock or later – yet most still need between eight and ten hours of sleep a night. When school starts at half past seven, the arithmetic does not work.",
  "Modern life makes it worse. The blue light from phones and laptops delays melatonin still further, tricking the brain into believing it is daytime. Social media is designed to be hard to put down, and messages that arrive late at night keep the mind alert. Homework, sport, part-time jobs and long journeys to school all squeeze the hours available for rest. Caffeine, now sold in large, sweet energy drinks aimed at young people, can stay in the body for many hours after an afternoon can.",
  "The consequences are serious. Tired teenagers find it harder to concentrate and to remember what they have learned, and their exam results can suffer. Lack of sleep is linked to low mood, anxiety and irritability, and to a greater risk of accidents, including on the roads. Over time, it may even affect physical health.",
  "Some schools have responded by pushing back the start of the school day, and the results have been striking: better attendance, fewer students falling asleep in class and, in some cases, improved grades. It is baffling that more schools have not followed their example, preferring timetables designed for the convenience of adults rather than the biology of the young people they are meant to serve.",
  "Teenagers themselves can help: switching off screens an hour before bed, keeping phones out of the bedroom and avoiding caffeine after lunch all make a difference. But it is unfair to ask young people to fight their own biology alone. The adults who design their days must play their part.",
 ]),
 C=dict(title="Moving Day", kind="Memoir", paras=[
  "The removal lorry arrived at seven, huge and yellow and utterly out of place in our narrow lane, where it sat with its engine rumbling like an impatient animal. By nine, the house I had lived in for all fourteen years of my life had been reduced to a <b>meagre</b> collection of cardboard boxes, each labelled in my mother’s firm black capitals: KITCHEN, BOOKS, FRAGILE.",
  "I walked through the empty rooms one last time. Without furniture they seemed larger and stranger, as though the house had been waiting all these years to shrug us off. My footsteps echoed on the bare floorboards. On the wall of my bedroom, a pale rectangle showed where my poster had hung and, beside the door, faint pencil lines climbed the frame – my height, measured every birthday, each line a little closer to the ceiling, like the rings inside a tree.",
  "Downstairs, my grandmother was sitting on the doorstep in the sun. She was not coming with us. She had decided, in the calm, <b>unshakeable</b> way she decided everything, that at eighty-one she was too old to learn a new city and too fond of her garden to leave it. She would move into the small flat above the bakery, two streets away, and her neighbour would keep an eye on her. I had argued, sulked and finally, shamefully, cried. She had simply patted my hand and said, “Houses are only boxes. People are what you take with you.”",
  "Now she handed me a small parcel wrapped in newspaper. Inside was a cutting from the fig tree that had grown by our back wall for longer than anyone could remember, its roots wrapped in damp cloth. “Plant it somewhere sunny,” she said. “It will sulk for a year, like you. Then it will grow.”",
  "The lorry pulled away first. We followed in the car, and I twisted in my seat to watch the house for as long as I could – the blue door, the crooked chimney, my grandmother’s hand raised in the doorway, growing smaller and smaller until the lane curved and swallowed them all. My chest ached with a strange, hollow pressure, as though something had been scooped out of it.",
  "That was six years ago. The fig tree stands in our new garden now, taller than I am. It sulked, exactly as she said it would, and then, one spring, it burst into leaf so suddenly that it seemed to have been waiting for permission. Every summer I send her a photograph of the first figs. Every summer she writes back the same three words: I told you.",
 ]),
 Q1=[
  ("How long had the Rex Cinema been showing films?", 1),
  ("Give <b>two</b> details from paragraph 2 which show that Mr Desai has worked at the cinema for a long time.", 2),
  ("Re-read paragraph 3. What does the comparison of the projector to “a great black animal asleep in its stall” suggest?", 2),
  ("Why do you think Mr Desai asked for the final film to be shown “the old way”?", 2),
  ("Using your own words, explain what Priya notices about her grandfather’s hands as he threads the film, and why this surprises her.", 3),
  ("“He smiled, but he did not look up from the reel.” What does this suggest about his feelings about retiring?", 2),
  ("According to Priya, why might so many people have come to the final screening?", 2),
  ("Explain what the comparison “the way a doctor listens to a heartbeat” suggests about Mr Desai.", 2),
  ("Explain why the ending is moving. Refer to both the audience and Mr Desai.", 4),
 ],
 Q1_ms=[
  "Sixty-two years (1).",
  "Any two: he arrived at five “as he always did”; he had carried the key for forty years; he did this every night of her mother’s childhood (accept) (1 each).",
  "The projector is large / powerful / old (1); it seems almost alive, resting, waiting to be woken – and cared for, like an animal (1).",
  "A tribute to his career / the cinema’s history (1); one last chance to use his skill / say goodbye properly / sentimental attachment (1).",
  "Up to 3: normally his fingers are stiff / clumsy (e.g. with buttons) (1); now they are skilful, smooth, precise and efficient (1); she has never seen him at work – she discovers a hidden side of him (1).",
  "He is hiding sadness / uncertainty (1); the joke covers his emotion; not meeting her eye avoids the question (1).",
  "The cinema is part of their personal history – first dates (1); bringing their own children to Saturday matinees; nostalgia / wanting to say goodbye (1).",
  "He is attentive / expert (1); he knows the machine’s sounds intimately and cares for it as if it were alive / checks its “health” (1).",
  "Up to 4: the audience stays and turns to the window – recognition of the unseen projectionist after years (1); their applause shows gratitude / respect for his work (1); his stillness then slowly raised hand shows how moved / humble he is (1); he cries but “did not mind” – he accepts his emotion; pride and a sense of closure (1).",
 ],
 Q2a=("According to Text B, why do many teenagers not get enough sleep?", [
  "the body clock shifts during adolescence",
  "melatonin is released about two hours later, so they feel sleepy later",
  "many do not feel tired until eleven or later",
  "they still need eight to ten hours’ sleep",
  "school starts early",
  "blue light from screens delays melatonin further / tricks the brain",
  "social media is designed to be hard to stop using",
  "late-night messages keep the mind alert",
  "homework reduces time for rest",
  "sport / part-time jobs take up time",
  "long journeys to school",
  "caffeine / energy drinks stay in the body for hours",
 ]),
 Q2b=("What is the writer’s attitude towards schools and the adults who run them? Explain how you can tell.", [
  "Critical of schools that keep early starts: it is “baffling” that more have not changed.",
  "Accuses them of putting adults first: timetables “designed for the convenience of adults rather than the biology of the young people”.",
  "Approving of schools that have changed: the results “have been striking”.",
  "Believes adults share responsibility: “must play their part”; “unfair to ask young people to fight their own biology alone”.",
  "Sympathetic to teenagers, rejecting the adult assumption of “laziness”.",
 ]),
 Q3s=[
  ("Using your own words, explain what the following words mean as they are used in the text:<br>(i) <b>meagre</b> (paragraph 1)", 2),
  ("(ii) <b>unshakeable</b> (paragraph 3)", 2),
  ("Re-read paragraph 2. Why does the writer compare the pencil lines to “the rings inside a tree”?", 2),
  ("Re-read paragraph 3. How did the writer react to the grandmother’s decision, and how does the writer feel about that reaction now?", 2),
  ("Re-read paragraph 4. What does the grandmother mean when she says the fig tree “will sulk for a year, like you”?", 2),
 ],
 Q3s_ms=[
  "Small / scanty / pitifully little (2). Award 1 for “few”.",
  "Firm / determined / impossible to change or persuade (2). Award 1 for “strong”.",
  "Both record growth over the years (1); they mark the passage of the writer’s childhood as a permanent part of the house (1).",
  "Upset – argued, sulked and cried (1); now feels ashamed / embarrassed – “shamefully” (1).",
  "Like the writer, the tree will struggle / not thrive at first after being moved (1); but it will recover and grow – reassurance that the writer will too (1).",
 ],
 Q3l=("Re-read paragraphs 2 and 5. Explain how the writer uses language to convey the feelings of leaving home.", [
  ("Paragraph 2", [
   "“one last time” – finality; a ritual goodbye.",
   "“larger and stranger” – the familiar made unfamiliar; alienation.",
   "“waiting all these years to shrug us off” – personified house, careless and indifferent; the writer feels rejected.",
   "“footsteps echoed on the bare floorboards” – emptiness, loneliness; sound emphasises absence.",
   "“a pale rectangle” – a trace of what is gone; memory made visible.",
   "“pencil lines climbed the frame… like the rings inside a tree” – childhood growth rooted in the house; leaving is like uprooting.",
  ]),
  ("Paragraph 5", [
   "“twisted in my seat to watch… for as long as I could” – desperation to hold on; reluctance to let go.",
   "list: “the blue door, the crooked chimney, my grandmother’s hand” – loving, specific details; the grandmother placed among the things being lost.",
   "“growing smaller and smaller” – repetition slows the moment; gradual, painful separation.",
   "“the lane curved and swallowed them all” – personified; the past devoured, gone for good.",
   "“chest ached with a strange, hollow pressure” – grief felt physically; “hollow” suggests emptiness.",
   "“as though something had been scooped out of it” – a violent, intimate image of loss, as if part of the writer has been removed.",
  ]),
 ]),
 Q4=("Imagine you are the grandmother. On the evening of moving day you write a journal entry.",
  ["describe your thoughts and feelings as you watched the family pack and leave",
   "explain why you decided to stay and why you gave your grandchild the fig cutting",
   "reflect on your hopes and worries for your grandchild and for yourself."],
  "journal",
  [("Bullet 1", "The loud yellow lorry in the narrow lane; the house emptied into labelled boxes; sitting on the doorstep in the sun; the grandchild walking through the rooms; the car pulling away; raising a hand until the lane curved – likely sadness hidden behind calm."),
   ("Bullet 2", "At eighty-one, too old to learn a new city; love of her garden; a small flat above the bakery two streets away with a neighbour nearby. The fig cutting: a living link to the old home; her belief that “people are what you take with you”; a lesson that the child, like the tree, will struggle and then grow."),
   ("Bullet 3 (inference – best answers develop this)", "Hopes: the grandchild will settle, grow and plant the fig somewhere sunny; the family will keep in touch. Worries: loneliness; the grandchild’s tears and sulking; ageing and her health. Her calm wisdom and quiet confidence (she will later write “I told you”).")]),
),
]
