"""Content for the IGCSE 0500 Composition Pack (Paper 2 Section B). All writing is original."""

SETS = [
 dict(n=1, d=["Describe a busy airport arrivals hall late at night.",
              "Describe a place in the moments before a storm breaks."],
      s=["Write a story that begins: ‘Nobody noticed when the lights went out.’",
         "Write a story called ‘The Return’."]),
 dict(n=2, d=["Describe a market as it closes at the end of the day.",
              "Describe an elderly person’s hands, and what they reveal about the life they have lived."],
      s=["Write a story about a secret that should never have been told.",
         "Write a story that ends with the words: ‘…and I never went back.’"]),
 dict(n=3, d=["Describe the view from a high place at dawn.",
              "Describe a school building during the summer holidays, when it is empty."],
      s=["Write a story about a journey that did not go as planned.",
         "Write a story called ‘The Letter’."]),
 dict(n=4, d=["Describe a crowded beach in summer, and then the same beach on a winter morning.",
              "Describe a kitchen in which a family meal is being prepared."],
      s=["Write a story in which a character has to make a difficult choice.",
         "Write a story that begins with a knock at the door."]),
 dict(n=5, d=["Describe a train station as a long-distance train departs.",
              "Describe a garden that has been abandoned for many years."],
      s=["Write a story about a competition.",
         "Write a story called ‘The Last Day’."]),
]

MODELS = [
 dict(kind="Descriptive", set=2, title="Describe a market as it closes at the end of the day.",
  text=[
   "At six o’clock the light changes. The sun, which has hammered the market all afternoon, slides behind the minaret and leaves the lanes in a soft, honey-coloured haze, as though the whole place has breathed out.",
   "The noise changes too. The fierce bargaining of midday has gone; in its place come the smaller sounds of an ending. Metal shutters rattle down one by one. Crates scrape across concrete. Somewhere a radio plays an old love song, half-drowned by the hiss of a hose washing fish scales into the gutter, where they glitter like spilled sequins.",
   "At the fruit stall, Abu Karim is dismantling his last pyramid of the day, lifting down the bruised mangoes and split figs and setting them aside in a cardboard box. His hands are quick and brown and scarred, and they never hesitate: he knows the weight of every fruit without looking. A thin cat watches from beneath the table, its tail twitching, patient as a tax collector.",
   "Further along, the spice sellers are folding their sacks. Each fold releases a ghost of what was sold – cumin, cardamom, a sharp breath of dried lime – so that walking down the lane is like turning the pages of a recipe book. A boy sweeps turmeric dust into the air, where it hangs, glowing, in the last slanting beams of light.",
   "People drift away. A woman balances a sack of rice on one hip and a sleeping toddler on the other. Two old men who have argued about football at the same table for thirty years shake hands solemnly, knowing they will meet again tomorrow at nine.",
   "By seven, the lanes are almost empty. The stalls stand bare and skeletal, their awnings rolled up like closed eyelids. Only the smell remains, rich and layered, clinging to the walls as though the market refuses to leave entirely. Then the street lamps flicker on, one after another, laying circles of orange light on the wet stones.",
   "The cat slips out from under the table, takes the fish head someone has left for it, and vanishes into the dark. The market is asleep. Tomorrow, before the sun, it will wake again.",
  ],
  notes=["<b>Structure:</b> moves from a wide view (light) to sound, zooms in on one person, widens again, then shifts in time (six to seven o’clock) and ends with a return to stillness.",
         "<b>Senses:</b> sight, sound, smell and touch are all used, and the smells in paragraph 4 are specific (cumin, cardamom, dried lime) rather than general.",
         "<b>Imagery:</b> fresh similes (“patient as a tax collector”, “like turning the pages of a recipe book”) instead of clichés.",
         "<b>No plot:</b> people move and act, but nothing “happens”. The piece stays descriptive, as the task requires.",
         "<b>Cohesion:</b> the cat appears in paragraph 3 and returns at the end, giving a satisfying shape."]),
 dict(kind="Descriptive", set=3, title="Describe a school building during the summer holidays, when it is empty.",
  text=[
   "In August, the school belongs to the heat.",
   "The gates are chained. Beyond them, the playground stretches out, pale and blinding, its painted lines faded to the ghosts of old games. Nothing moves except the air above the tarmac, which trembles like water. A single forgotten water bottle lies by the fence, warped into a strange, melted shape by weeks of sun.",
   "Inside, the corridors hold their breath. Without the stampede of feet and the shriek of the bell, the silence is so complete that the building seems larger, as if it has stretched out to rest. The only sounds are the tired hum of a drinks machine near the canteen and the occasional tick of metal expanding in the heat.",
   "The classrooms are strange without their students. Chairs have been stacked upside-down on the desks, their legs pointing at the ceiling like the limbs of dead insects. Sunlight squeezes through the blinds and lies across the floor in thin stripes, and in each stripe the dust drifts and turns, slow and golden, the only thing in the room that still seems alive.",
   "In Room 14, someone has forgotten to clean the whiteboard. Half a sentence remains in faded blue marker: <i>The main theme of the poem is</i>. The rest has been wiped away by a careless sleeve, and the sentence hangs there, unfinished, waiting for an answer that will not come until September.",
   "On the walls, the displays are curling at the edges. A poster of the water cycle has slipped from one of its pins and hangs at an angle, as if it too has given up for the summer. A row of self-portraits by eleven-year-olds – wild orange hair, enormous smiles, eyes that do not quite match – gaze out at nobody, their bright colours already fading like the memory of a noisier time.",
   "Late in the afternoon, the caretaker crosses the courtyard with a jangling ring of keys, the only person in the whole enormous building. He tests a door, checks a window, and pauses to look at the empty playground, as if listening for something. Then he locks the gate behind him, and the school settles back into its long, patient sleep.",
  ],
  notes=["<b>Opening:</b> a short, striking one-sentence paragraph establishes mood at once.",
         "<b>Personification</b> (“the corridors hold their breath”) makes the building feel alive but sleeping, a controlling idea that returns in the final line.",
         "<b>Precise detail:</b> the unfinished sentence on the whiteboard is a small, specific image that suggests absence far better than “it was empty”.",
         "<b>Contrast:</b> the imagined noise of term time sharpens the silence of the holidays.",
         "<b>Sentence variety:</b> short sentences (“The gates are chained.”) alongside long, flowing ones."]),
 dict(kind="Narrative", set=1, title="Write a story that begins: ‘Nobody noticed when the lights went out.’",
  text=[
   "Nobody noticed when the lights went out.",
   "My mother was scrolling through work emails, my brother was hunched over a game, and I was rewriting the same message to Lina for the fourth time. Our screens glowed on, bright and faithful, and it was a full minute before my brother looked up and said, ‘Why’s it so dark?’",
   "Outside, the storm had finally arrived. Rain lashed the windows of Grandpa’s flat and the whole street had vanished into blackness. Then the Wi-Fi died, and one by one our phones followed, until the only sound was the old clock on the bookcase – a sound I had never noticed in fourteen years of visits.",
   "That was when I realised Grandpa’s chair was empty.",
   "Since his illness began, Grandpa had become almost a piece of furniture. He sat by the window in his cardigan, smiling politely at us as though we were strangers. Some days he called me by my mother’s name. Some days he called me nothing at all.",
   "‘Grandpa?’ My voice sounded thin in the dark.",
   "We found him in the kitchen. Somehow he had found a candle and lit it, and he was standing at the counter, his face glowing gold, his hands steady, pouring tea into four glasses.",
   "‘Sit,’ he said. ‘When the lights go, you sit together. That is the rule.’",
   "So we sat, and in the small circle of candlelight he began to talk. He told us about his village, where the electricity failed every summer and his mother told stories until the children fell asleep. He told us about meeting my grandmother at a wedding where the generator broke and everyone danced to a single drum. He laughed – a real laugh, one I had forgotten he owned.",
   "Then he looked straight at me. ‘Yasmin,’ he said. ‘You have your grandmother’s eyes.’",
   "It was the first time he had said my name in a year.",
   "The lights came back at half past eleven. The fridge shuddered into life and our phones began to buzz. When I looked back at Grandpa, the brightness had already drained from his face.",
   "I kept the candle. Some nights, I switch off my lamp and light it, and for a few minutes I am back in that kitchen, and he knows my name.",
  ],
  notes=["<b>Hook:</b> uses the given opening, then immediately shows why nobody noticed (the screens), turning the line into a theme.",
         "<b>One central event, few characters:</b> the whole story happens in one evening in one flat.",
         "<b>Complication:</b> the empty chair creates tension and a turning point.",
         "<b>Show, don’t tell:</b> Grandpa’s illness is shown through what he calls people, not explained in medical terms.",
         "<b>Climax in a single line:</b> “You have your grandmother’s eyes.” A short paragraph follows to let it land.",
         "<b>Ending:</b> the candle is an object that carries the meaning forward. The ending is reflective, and neither rushed nor explained."]),
 dict(kind="Narrative", set=3, title="Write a story called ‘The Letter’.",
  text=[
   "The letter was shorter than I remembered, and the handwriting was enormous.",
   "On the last day of Year 11, Mr Hadid dragged the time capsule out of the storeroom and handed out the envelopes, reading our names like a register. Around me, people were already laughing at their eleven-year-old selves. I opened mine carefully, as if it might explode.",
   "<i>Dear Future Me</i>, it said, in purple gel pen. <i>I hope you are still drawing every day. If you haven’t told Dad yet that you want to be an artist, DO IT TODAY. Love, Me. P.S. Is Mimi the cat still alive?</i>",
   "Mimi was still alive. Nothing else in the letter was.",
   "I had not drawn anything except diagrams of the heart in almost three years. When it was time to choose my subjects, Dad had spread the brochures across the kitchen table like playing cards and talked about security and ‘a real future’. He had worked two jobs for most of my life so that I could have exactly that. So I chose the sciences, and my sketchbooks went into a box under the bed.",
   "I carried the letter home in my pocket, where it seemed to grow heavier with every step. Dad was in the kitchen, still in his work shirt, frying onions. He looked tired. He always looked tired.",
   "I put the letter on the counter beside the chopping board and watched him read it. The onions hissed. He read it twice. Then, without a word, he turned off the cooker and left the room.",
   "My heart was hammering. I heard something heavy being dragged across the floor of the spare room. When he came back, he was holding a cardboard folder, soft and faded at the corners.",
   "Inside were my drawings – the lopsided cats, the dragons, the portraits of him with an enormous moustache he had never actually had. He had kept every single one.",
   "‘I thought you’d stopped because you wanted to,’ he said quietly. ‘You should have told me.’",
   "‘I’m telling you now,’ I said.",
   "That evening, I pulled the box out from under my bed. I drew Dad at the kitchen table, reading a letter, and I gave him the moustache.",
  ],
  notes=["<b>Opening:</b> begins with the object in the title and a small, intriguing detail (“the handwriting was enormous”).",
         "<b>Backstory in one paragraph:</b> the father’s sacrifice is explained quickly, so the reader understands the character’s dilemma.",
         "<b>Tension through delay:</b> the father leaves the room without speaking; short sentences (“The onions hissed.”) slow the moment.",
         "<b>Twist that grows from character:</b> the folder of drawings reverses what the narrator (and reader) expected.",
         "<b>Dialogue:</b> only three lines, each one doing real work.",
         "<b>Circular ending:</b> the moustache links back to the drawings, ending with warmth and humour."]),
]

UPGRADES = [
 ("The sun was very hot.", "The sun pressed down on the car roofs until the metal ticked and shimmered.", "Show the heat through its effects; use precise verbs."),
 ("I was very nervous before the race.", "My legs felt borrowed. I retied my laces for the third time, just to have something to do with my hands.", "Show, don’t tell: reveal the feeling through the body and actions."),
 ("The forest was dark and scary.", "Beneath the pines, the daylight thinned to a green dusk, and every snapped twig sounded like a footstep.", "Build atmosphere with light and sound instead of labelling it."),
 ("There were lots of people at the station.", "Travellers poured from the escalators in a tide of suitcases, elbows and hurried apologies.", "Use a controlling metaphor and a list of specific nouns."),
 ("Suddenly there was a loud noise.", "The crash came from the kitchen – a single, splintering note, and then silence.", "Avoid “suddenly”; name the sound precisely; use a dash for impact."),
 ("She was old and kind.", "Her face was creased like a well-read letter, and she never let anyone leave her house without something wrapped in foil.", "Characterise through a fresh simile and a typical action."),
 ("It was a nice day at the beach.", "The sea lay flat and glittering, and the air smelled of salt, sun cream and frying fish.", "Replace vague adjectives with sensory detail."),
 ("In conclusion, it was the best day of my life.", "Even now, when I smell charcoal smoke, I am back on that rooftop, twelve years old, the whole city spread beneath me like a promise.", "End with a sensory memory, not a summary."),
]
